//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VA.TMP.OptionSets;

namespace VA.TMP.DataModel
{
    /// <summary>
    /// 
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("cvt_patientresourcegroup")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public partial class cvt_patientresourcegroup : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public cvt_patientresourcegroup(): base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "cvt_patientresourcegroup";
        public const string EntityLogicalCollectionName = "cvt_patientresourcegroups";
        public const string EntitySetName = "cvt_patientresourcegroups";
        public const int EntityTypeCode = 10003;
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        private void OnPropertyChanging(string propertyName)
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_capacityrequired")]
        public System.Nullable<int> cvt_CapacityRequired
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("cvt_capacityrequired");
            }

            set
            {
                this.OnPropertyChanging("cvt_CapacityRequired");
                this.SetAttributeValue("cvt_capacityrequired", value);
                this.OnPropertyChanged("cvt_CapacityRequired");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_constraintgroupguid")]
        public string cvt_constraintgroupguid
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_constraintgroupguid");
            }

            set
            {
                this.OnPropertyChanging("cvt_constraintgroupguid");
                this.SetAttributeValue("cvt_constraintgroupguid", value);
                this.OnPropertyChanged("cvt_constraintgroupguid");
            }
        }

        /// <summary>
        /// The name of the custom entity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_name")]
        public string cvt_name
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_name");
            }

            set
            {
                this.OnPropertyChanging("cvt_name");
                this.SetAttributeValue("cvt_name", value);
                this.OnPropertyChanged("cvt_name");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_patientcount")]
        public System.Nullable<int> cvt_patientcount
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("cvt_patientcount");
            }

            set
            {
                this.OnPropertyChanging("cvt_patientcount");
                this.SetAttributeValue("cvt_patientcount", value);
                this.OnPropertyChanged("cvt_patientcount");
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_patientresourcegroupid")]
        public System.Nullable<System.Guid> cvt_patientresourcegroupId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("cvt_patientresourcegroupid");
            }

            set
            {
                this.OnPropertyChanging("cvt_patientresourcegroupId");
                this.SetAttributeValue("cvt_patientresourcegroupid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }

                this.OnPropertyChanged("cvt_patientresourcegroupId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_patientresourcegroupid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }

            set
            {
                this.cvt_patientresourcegroupId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_patients")]
        public System.Nullable<int> cvt_patients
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("cvt_patients");
            }

            set
            {
                this.OnPropertyChanging("cvt_patients");
                this.SetAttributeValue("cvt_patients", value);
                this.OnPropertyChanged("cvt_patients");
            }
        }

        /// <summary>
        /// Unique identifier for Resource Group associated with Patient Resource Group.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedresourcegroupid")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_RelatedResourceGroupid
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_relatedresourcegroupid");
            }

            set
            {
                this.OnPropertyChanging("cvt_RelatedResourceGroupid");
                this.SetAttributeValue("cvt_relatedresourcegroupid", value);
                this.OnPropertyChanged("cvt_RelatedResourceGroupid");
            }
        }

        /// <summary>
        /// Unique identifier for Resource associated with Patient Resource Group.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedresourceid")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_RelatedResourceId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_relatedresourceid");
            }

            set
            {
                this.OnPropertyChanging("cvt_RelatedResourceId");
                this.SetAttributeValue("cvt_relatedresourceid", value);
                this.OnPropertyChanged("cvt_RelatedResourceId");
            }
        }

        /// <summary>
        /// Unique identifier for MCS Site associated with Patient Resource Group.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedsiteid")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_relatedsiteid
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_relatedsiteid");
            }

            set
            {
                this.OnPropertyChanging("cvt_relatedsiteid");
                this.SetAttributeValue("cvt_relatedsiteid", value);
                this.OnPropertyChanged("cvt_relatedsiteid");
            }
        }

        /// <summary>
        /// Unique identifier for TSA associated with Patient Resource Group.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedtsaid")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_RelatedTSAid
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_relatedtsaid");
            }

            set
            {
                this.OnPropertyChanging("cvt_RelatedTSAid");
                this.SetAttributeValue("cvt_relatedtsaid", value);
                this.OnPropertyChanged("cvt_RelatedTSAid");
            }
        }

        /// <summary>
        /// Unique identifier for User associated with Patient Resource Group.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relateduserid")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_RelatedUserId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_relateduserid");
            }

            set
            {
                this.OnPropertyChanging("cvt_RelatedUserId");
                this.SetAttributeValue("cvt_relateduserid", value);
                this.OnPropertyChanged("cvt_RelatedUserId");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_resourcespecguid")]
        public string cvt_resourcespecguid
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_resourcespecguid");
            }

            set
            {
                this.OnPropertyChanging("cvt_resourcespecguid");
                this.SetAttributeValue("cvt_resourcespecguid", value);
                this.OnPropertyChanged("cvt_resourcespecguid");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_roomcapacity")]
        public System.Nullable<int> cvt_roomcapacity
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("cvt_roomcapacity");
            }

            set
            {
                this.OnPropertyChanging("cvt_roomcapacity");
                this.SetAttributeValue("cvt_roomcapacity", value);
                this.OnPropertyChanged("cvt_roomcapacity");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_tsaresourcetype")]
        public Microsoft.Xrm.Sdk.OptionSetValue cvt_TSAResourceType
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("cvt_tsaresourcetype");
                if ((optionSet != null))
                {
                    return optionSet;
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("cvt_TSAResourceType");
                if ((value == null))
                {
                    this.SetAttributeValue("cvt_tsaresourcetype", null);
                }
                else
                {
                    this.SetAttributeValue("cvt_tsaresourcetype", value);
                }

                this.OnPropertyChanged("cvt_TSAResourceType");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_type")]
        public Microsoft.Xrm.Sdk.OptionSetValue cvt_type
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("cvt_type");
                if ((optionSet != null))
                {
                    return optionSet;
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("cvt_type");
                if ((value == null))
                {
                    this.SetAttributeValue("cvt_type", null);
                }
                else
                {
                    this.SetAttributeValue("cvt_type", value);
                }

                this.OnPropertyChanged("cvt_type");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_vistaclinicname")]
        public string cvt_vistaclinicname
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_vistaclinicname");
            }

            set
            {
                this.OnPropertyChanging("cvt_vistaclinicname");
                this.SetAttributeValue("cvt_vistaclinicname", value);
                this.OnPropertyChanged("cvt_vistaclinicname");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }

            set
            {
                this.OnPropertyChanging("ImportSequenceNumber");
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }

            set
            {
                this.OnPropertyChanging("OverriddenCreatedOn");
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("OverriddenCreatedOn");
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }

            set
            {
                this.OnPropertyChanging("OwnerId");
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("OwnerId");
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Status of the Patient Resource Group
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public System.Nullable<cvt_patientresourcegroupState> statecode
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((cvt_patientresourcegroupState)(System.Enum.ToObject(typeof(cvt_patientresourcegroupState), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("statecode");
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("statecode");
            }
        }

        /// <summary>
        /// Reason for the status of the Patient Resource Group
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public System.Nullable<cvt_patientresourcegroup_statuscode> statuscode
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
                if ((optionSet != null))
                {
                    return ((cvt_patientresourcegroup_statuscode)(System.Enum.ToObject(typeof(cvt_patientresourcegroup_statuscode), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("statuscode");
                if ((value == null))
                {
                    this.SetAttributeValue("statuscode", null);
                }
                else
                {
                    this.SetAttributeValue("statuscode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("statuscode");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }

            set
            {
                this.OnPropertyChanging("TimeZoneRuleVersionNumber");
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }

            set
            {
                this.OnPropertyChanging("UTCConversionTimeZoneCode");
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// 1:N cvt_cvt_patientresourcegroup_mcs_patientsiteroom_relatedpatientsiteresourceid
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_cvt_patientresourcegroup_mcs_patientsiteroom_relatedpatientsiteresourceid")]
        public System.Collections.Generic.IEnumerable<PatientSiteRoom> PatientSiteRooms_PatientSiteResource
        {
            get
            {
                return this.GetRelatedEntities<PatientSiteRoom>("cvt_cvt_patientresourcegroup_mcs_patientsiteroom_relatedpatientsiteresourceid", null);
            }

            set
            {
                this.OnPropertyChanging("PatientSiteRooms_PatientSiteResource");
                this.SetRelatedEntities<PatientSiteRoom>("cvt_cvt_patientresourcegroup_mcs_patientsiteroom_relatedpatientsiteresourceid", null, value);
                this.OnPropertyChanged("PatientSiteRooms_PatientSiteResource");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_ActivityPointers
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_ActivityPointers")]
        public System.Collections.Generic.IEnumerable<ActivityPointer> cvt_patientresourcegroup_ActivityPointers
        {
            get
            {
                return this.GetRelatedEntities<ActivityPointer>("cvt_patientresourcegroup_ActivityPointers", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_patientresourcegroup_ActivityPointers");
                this.SetRelatedEntities<ActivityPointer>("cvt_patientresourcegroup_ActivityPointers", null, value);
                this.OnPropertyChanged("cvt_patientresourcegroup_ActivityPointers");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_Annotations
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_Annotations")]
        public System.Collections.Generic.IEnumerable<Annotation> cvt_patientresourcegroup_Annotations
        {
            get
            {
                return this.GetRelatedEntities<Annotation>("cvt_patientresourcegroup_Annotations", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_patientresourcegroup_Annotations");
                this.SetRelatedEntities<Annotation>("cvt_patientresourcegroup_Annotations", null, value);
                this.OnPropertyChanged("cvt_patientresourcegroup_Annotations");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_Appointments
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_Appointments")]
        public System.Collections.Generic.IEnumerable<Appointment> cvt_patientresourcegroup_Appointments
        {
            get
            {
                return this.GetRelatedEntities<Appointment>("cvt_patientresourcegroup_Appointments", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_patientresourcegroup_Appointments");
                this.SetRelatedEntities<Appointment>("cvt_patientresourcegroup_Appointments", null, value);
                this.OnPropertyChanged("cvt_patientresourcegroup_Appointments");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_AsyncOperations
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_AsyncOperations")]
        public System.Collections.Generic.IEnumerable<SystemJob> SystemJobs_Regarding
        {
            get
            {
                return this.GetRelatedEntities<SystemJob>("cvt_patientresourcegroup_AsyncOperations", null);
            }

            set
            {
                this.OnPropertyChanging("SystemJobs_Regarding");
                this.SetRelatedEntities<SystemJob>("cvt_patientresourcegroup_AsyncOperations", null, value);
                this.OnPropertyChanged("SystemJobs_Regarding");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_BulkDeleteFailures
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_BulkDeleteFailures")]
        public System.Collections.Generic.IEnumerable<BulkDeleteFailure> BulkDeleteFailures_Name
        {
            get
            {
                return this.GetRelatedEntities<BulkDeleteFailure>("cvt_patientresourcegroup_BulkDeleteFailures", null);
            }

            set
            {
                this.OnPropertyChanging("BulkDeleteFailures_Name");
                this.SetRelatedEntities<BulkDeleteFailure>("cvt_patientresourcegroup_BulkDeleteFailures", null, value);
                this.OnPropertyChanged("BulkDeleteFailures_Name");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_connections1
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_connections1")]
        public System.Collections.Generic.IEnumerable<Connection> Connections_ConnectedFrom
        {
            get
            {
                return this.GetRelatedEntities<Connection>("cvt_patientresourcegroup_connections1", null);
            }

            set
            {
                this.OnPropertyChanging("Connections_ConnectedFrom");
                this.SetRelatedEntities<Connection>("cvt_patientresourcegroup_connections1", null, value);
                this.OnPropertyChanged("Connections_ConnectedFrom");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_connections2
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_connections2")]
        public System.Collections.Generic.IEnumerable<Connection> Connections_ConnectedTo
        {
            get
            {
                return this.GetRelatedEntities<Connection>("cvt_patientresourcegroup_connections2", null);
            }

            set
            {
                this.OnPropertyChanging("Connections_ConnectedTo");
                this.SetRelatedEntities<Connection>("cvt_patientresourcegroup_connections2", null, value);
                this.OnPropertyChanged("Connections_ConnectedTo");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_Emails
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_Emails")]
        public System.Collections.Generic.IEnumerable<Email> cvt_patientresourcegroup_Emails
        {
            get
            {
                return this.GetRelatedEntities<Email>("cvt_patientresourcegroup_Emails", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_patientresourcegroup_Emails");
                this.SetRelatedEntities<Email>("cvt_patientresourcegroup_Emails", null, value);
                this.OnPropertyChanged("cvt_patientresourcegroup_Emails");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_MailboxTrackingFolders
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_MailboxTrackingFolders")]
        public System.Collections.Generic.IEnumerable<MailboxAutoTrackingFolder> MailboxAutoTrackingFolders_RegardingObjectId
        {
            get
            {
                return this.GetRelatedEntities<MailboxAutoTrackingFolder>("cvt_patientresourcegroup_MailboxTrackingFolders", null);
            }

            set
            {
                this.OnPropertyChanging("MailboxAutoTrackingFolders_RegardingObjectId");
                this.SetRelatedEntities<MailboxAutoTrackingFolder>("cvt_patientresourcegroup_MailboxTrackingFolders", null, value);
                this.OnPropertyChanged("MailboxAutoTrackingFolders_RegardingObjectId");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_PrincipalObjectAttributeAccesses
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_PrincipalObjectAttributeAccesses")]
        public System.Collections.Generic.IEnumerable<FieldSharing> FieldSharing_EntityInstance
        {
            get
            {
                return this.GetRelatedEntities<FieldSharing>("cvt_patientresourcegroup_PrincipalObjectAttributeAccesses", null);
            }

            set
            {
                this.OnPropertyChanging("FieldSharing_EntityInstance");
                this.SetRelatedEntities<FieldSharing>("cvt_patientresourcegroup_PrincipalObjectAttributeAccesses", null, value);
                this.OnPropertyChanged("FieldSharing_EntityInstance");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_ProcessSession
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_ProcessSession")]
        public System.Collections.Generic.IEnumerable<ProcessSession> ProcessSessions_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ProcessSession>("cvt_patientresourcegroup_ProcessSession", null);
            }

            set
            {
                this.OnPropertyChanging("ProcessSessions_Regarding");
                this.SetRelatedEntities<ProcessSession>("cvt_patientresourcegroup_ProcessSession", null, value);
                this.OnPropertyChanged("ProcessSessions_Regarding");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_RecurringAppointmentMasters
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_RecurringAppointmentMasters")]
        public System.Collections.Generic.IEnumerable<RecurringAppointmentMaster> cvt_patientresourcegroup_RecurringAppointmentMasters
        {
            get
            {
                return this.GetRelatedEntities<RecurringAppointmentMaster>("cvt_patientresourcegroup_RecurringAppointmentMasters", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_patientresourcegroup_RecurringAppointmentMasters");
                this.SetRelatedEntities<RecurringAppointmentMaster>("cvt_patientresourcegroup_RecurringAppointmentMasters", null, value);
                this.OnPropertyChanged("cvt_patientresourcegroup_RecurringAppointmentMasters");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_ServiceAppointments
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_ServiceAppointments")]
        public System.Collections.Generic.IEnumerable<ServiceAppointment> cvt_patientresourcegroup_ServiceAppointments
        {
            get
            {
                return this.GetRelatedEntities<ServiceAppointment>("cvt_patientresourcegroup_ServiceAppointments", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_patientresourcegroup_ServiceAppointments");
                this.SetRelatedEntities<ServiceAppointment>("cvt_patientresourcegroup_ServiceAppointments", null, value);
                this.OnPropertyChanged("cvt_patientresourcegroup_ServiceAppointments");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_SyncErrors
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_SyncErrors")]
        public System.Collections.Generic.IEnumerable<SyncError> SyncErrors_Record
        {
            get
            {
                return this.GetRelatedEntities<SyncError>("cvt_patientresourcegroup_SyncErrors", null);
            }

            set
            {
                this.OnPropertyChanging("SyncErrors_Record");
                this.SetRelatedEntities<SyncError>("cvt_patientresourcegroup_SyncErrors", null, value);
                this.OnPropertyChanged("SyncErrors_Record");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_Tasks
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_Tasks")]
        public System.Collections.Generic.IEnumerable<Task> Tasks_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Task>("cvt_patientresourcegroup_Tasks", null);
            }

            set
            {
                this.OnPropertyChanging("Tasks_Regarding");
                this.SetRelatedEntities<Task>("cvt_patientresourcegroup_Tasks", null, value);
                this.OnPropertyChanged("Tasks_Regarding");
            }
        }

        /// <summary>
        /// 1:N cvt_patientresourcegroup_UserEntityInstanceDatas
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_patientresourcegroup_UserEntityInstanceDatas")]
        public System.Collections.Generic.IEnumerable<UserEntityInstanceData> UserEntityInstanceData_ObjectId
        {
            get
            {
                return this.GetRelatedEntities<UserEntityInstanceData>("cvt_patientresourcegroup_UserEntityInstanceDatas", null);
            }

            set
            {
                this.OnPropertyChanging("UserEntityInstanceData_ObjectId");
                this.SetRelatedEntities<UserEntityInstanceData>("cvt_patientresourcegroup_UserEntityInstanceDatas", null, value);
                this.OnPropertyChanged("UserEntityInstanceData_ObjectId");
            }
        }

        /// <summary>
        /// N:N cvt_cvt_patientresourcegroup_contact
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_cvt_patientresourcegroup_contact")]
        public System.Collections.Generic.IEnumerable<Contact> cvt_cvt_patientresourcegroup_contact
        {
            get
            {
                return this.GetRelatedEntities<Contact>("cvt_cvt_patientresourcegroup_contact", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_cvt_patientresourcegroup_contact");
                this.SetRelatedEntities<Contact>("cvt_cvt_patientresourcegroup_contact", null, value);
                this.OnPropertyChanged("cvt_cvt_patientresourcegroup_contact");
            }
        }

        /// <summary>
        /// N:1 business_unit_cvt_patientresourcegroup
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_cvt_patientresourcegroup")]
        public BusinessUnit business_unit_cvt_patientresourcegroup
        {
            get
            {
                return this.GetRelatedEntity<BusinessUnit>("business_unit_cvt_patientresourcegroup", null);
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_resource_cvt_patientresourcegroup
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedresourceid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_resource_cvt_patientresourcegroup")]
        public mcs_resource cvt_mcs_resource_cvt_patientresourcegroup
        {
            get
            {
                return this.GetRelatedEntity<mcs_resource>("cvt_mcs_resource_cvt_patientresourcegroup", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_resource_cvt_patientresourcegroup");
                this.SetRelatedEntity<mcs_resource>("cvt_mcs_resource_cvt_patientresourcegroup", null, value);
                this.OnPropertyChanged("cvt_mcs_resource_cvt_patientresourcegroup");
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_resourcegroup_cvt_patientresourcegroup_RelatedResourceGroupid
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedresourcegroupid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_resourcegroup_cvt_patientresourcegroup_RelatedResourceGroupid")]
        public mcs_resourcegroup cvt_mcs_resourcegroup_cvt_patientresourcegroup_RelatedResourceGroupid
        {
            get
            {
                return this.GetRelatedEntity<mcs_resourcegroup>("cvt_mcs_resourcegroup_cvt_patientresourcegroup_RelatedResourceGroupid", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_resourcegroup_cvt_patientresourcegroup_RelatedResourceGroupid");
                this.SetRelatedEntity<mcs_resourcegroup>("cvt_mcs_resourcegroup_cvt_patientresourcegroup_RelatedResourceGroupid", null, value);
                this.OnPropertyChanged("cvt_mcs_resourcegroup_cvt_patientresourcegroup_RelatedResourceGroupid");
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedtsaid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid")]
        public mcs_services cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid
        {
            get
            {
                return this.GetRelatedEntity<mcs_services>("cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid");
                this.SetRelatedEntity<mcs_services>("cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid", null, value);
                this.OnPropertyChanged("cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid");
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_site_cvt_patientresourcegroup_relatedsiteid
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedsiteid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_site_cvt_patientresourcegroup_relatedsiteid")]
        public mcs_site cvt_mcs_site_cvt_patientresourcegroup_relatedsiteid
        {
            get
            {
                return this.GetRelatedEntity<mcs_site>("cvt_mcs_site_cvt_patientresourcegroup_relatedsiteid", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_site_cvt_patientresourcegroup_relatedsiteid");
                this.SetRelatedEntity<mcs_site>("cvt_mcs_site_cvt_patientresourcegroup_relatedsiteid", null, value);
                this.OnPropertyChanged("cvt_mcs_site_cvt_patientresourcegroup_relatedsiteid");
            }
        }

        /// <summary>
        /// N:1 cvt_systemuser_cvt_patientresourcegroup
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relateduserid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_systemuser_cvt_patientresourcegroup")]
        public SystemUser cvt_systemuser_cvt_patientresourcegroup
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("cvt_systemuser_cvt_patientresourcegroup", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_systemuser_cvt_patientresourcegroup");
                this.SetRelatedEntity<SystemUser>("cvt_systemuser_cvt_patientresourcegroup", null, value);
                this.OnPropertyChanged("cvt_systemuser_cvt_patientresourcegroup");
            }
        }

        /// <summary>
        /// N:1 lk_cvt_patientresourcegroup_createdby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_cvt_patientresourcegroup_createdby")]
        public SystemUser lk_cvt_patientresourcegroup_createdby
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_cvt_patientresourcegroup_createdby", null);
            }
        }

        /// <summary>
        /// N:1 lk_cvt_patientresourcegroup_createdonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_cvt_patientresourcegroup_createdonbehalfby")]
        public SystemUser lk_cvt_patientresourcegroup_createdonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_cvt_patientresourcegroup_createdonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 lk_cvt_patientresourcegroup_modifiedby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_cvt_patientresourcegroup_modifiedby")]
        public SystemUser lk_cvt_patientresourcegroup_modifiedby
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_cvt_patientresourcegroup_modifiedby", null);
            }
        }

        /// <summary>
        /// N:1 lk_cvt_patientresourcegroup_modifiedonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_cvt_patientresourcegroup_modifiedonbehalfby")]
        public SystemUser lk_cvt_patientresourcegroup_modifiedonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_cvt_patientresourcegroup_modifiedonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 team_cvt_patientresourcegroup
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_cvt_patientresourcegroup")]
        public Team team_cvt_patientresourcegroup
        {
            get
            {
                return this.GetRelatedEntity<Team>("team_cvt_patientresourcegroup", null);
            }
        }

        /// <summary>
        /// N:1 user_cvt_patientresourcegroup
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_cvt_patientresourcegroup")]
        public SystemUser user_cvt_patientresourcegroup
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("user_cvt_patientresourcegroup", null);
            }
        }
    }
}