//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using VA.TMP.DataModel.OptionSets;

namespace VA.TMP.DataModel
{
    /// <summary>
    /// 
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("mcs_interface")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public partial class InterfaceDefinition : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public InterfaceDefinition(): base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "mcs_interface";
        public const string EntityLogicalCollectionName = "mcs_interfaces";
        public const string EntitySetName = "mcs_interfaces";
        public const int EntityTypeCode = 10021;
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        private void OnPropertyChanging(string propertyName)
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy_Delegate
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }

            set
            {
                this.OnPropertyChanging("ImportSequenceNumber");
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_averagelagtime")]
        public System.Nullable<int> AverageLagTime_ms
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("mcs_averagelagtime");
            }

            set
            {
                this.OnPropertyChanging("AverageLagTime_ms");
                this.SetAttributeValue("mcs_averagelagtime", value);
                this.OnPropertyChanged("AverageLagTime_ms");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_averageprocessingtime")]
        public System.Nullable<int> AverageProcessingTime_ms
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("mcs_averageprocessingtime");
            }

            set
            {
                this.OnPropertyChanging("AverageProcessingTime_ms");
                this.SetAttributeValue("mcs_averageprocessingtime", value);
                this.OnPropertyChanged("AverageProcessingTime_ms");
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_interfaceid")]
        public System.Nullable<System.Guid> InterfaceId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("mcs_interfaceid");
            }

            set
            {
                this.OnPropertyChanging("InterfaceId");
                this.SetAttributeValue("mcs_interfaceid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }

                this.OnPropertyChanged("InterfaceId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_interfaceid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }

            set
            {
                this.InterfaceId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_interfacerunmode")]
        public System.Nullable<InterfaceDefinition_RunMode> RunMode
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mcs_interfacerunmode");
                if ((optionSet != null))
                {
                    return ((InterfaceDefinition_RunMode)(System.Enum.ToObject(typeof(InterfaceDefinition_RunMode), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("RunMode");
                if ((value == null))
                {
                    this.SetAttributeValue("mcs_interfacerunmode", null);
                }
                else
                {
                    this.SetAttributeValue("mcs_interfacerunmode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("RunMode");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_messagesaccepted")]
        public System.Nullable<int> MessagesAccepted
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("mcs_messagesaccepted");
            }

            set
            {
                this.OnPropertyChanging("MessagesAccepted");
                this.SetAttributeValue("mcs_messagesaccepted", value);
                this.OnPropertyChanged("MessagesAccepted");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_messagespending")]
        public System.Nullable<int> MessagesPending
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("mcs_messagespending");
            }

            set
            {
                this.OnPropertyChanging("MessagesPending");
                this.SetAttributeValue("mcs_messagespending", value);
                this.OnPropertyChanged("MessagesPending");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_messagesrejected")]
        public System.Nullable<int> MessagesRejected
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("mcs_messagesrejected");
            }

            set
            {
                this.OnPropertyChanging("MessagesRejected");
                this.SetAttributeValue("mcs_messagesrejected", value);
                this.OnPropertyChanged("MessagesRejected");
            }
        }

        /// <summary>
        /// The name of the custom entity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_name")]
        public string Name
        {
            get
            {
                return this.GetAttributeValue<string>("mcs_name");
            }

            set
            {
                this.OnPropertyChanging("Name");
                this.SetAttributeValue("mcs_name", value);
                this.OnPropertyChanged("Name");
            }
        }

        /// <summary>
        /// The method that is used to process the event to / from VIMT
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_processingmode")]
        public System.Nullable<InterfaceDefinition_ProcessingMode> ProcessingMode
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mcs_processingmode");
                if ((optionSet != null))
                {
                    return ((InterfaceDefinition_ProcessingMode)(System.Enum.ToObject(typeof(InterfaceDefinition_ProcessingMode), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("ProcessingMode");
                if ((value == null))
                {
                    this.SetAttributeValue("mcs_processingmode", null);
                }
                else
                {
                    this.SetAttributeValue("mcs_processingmode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("ProcessingMode");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_status")]
        public System.Nullable<InterfaceDefinition_Status> InterfaceStatus
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mcs_status");
                if ((optionSet != null))
                {
                    return ((InterfaceDefinition_Status)(System.Enum.ToObject(typeof(InterfaceDefinition_Status), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("InterfaceStatus");
                if ((value == null))
                {
                    this.SetAttributeValue("mcs_status", null);
                }
                else
                {
                    this.SetAttributeValue("mcs_status", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("InterfaceStatus");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_type")]
        public System.Nullable<InterfaceDefinition_Type> Type
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mcs_type");
                if ((optionSet != null))
                {
                    return ((InterfaceDefinition_Type)(System.Enum.ToObject(typeof(InterfaceDefinition_Type), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("Type");
                if ((value == null))
                {
                    this.SetAttributeValue("mcs_type", null);
                }
                else
                {
                    this.SetAttributeValue("mcs_type", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("Type");
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy_Delegate
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> RecordCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }

            set
            {
                this.OnPropertyChanging("RecordCreatedOn");
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("RecordCreatedOn");
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference Owner
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }

            set
            {
                this.OnPropertyChanging("Owner");
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("Owner");
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Status of the Interface
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public System.Nullable<InterfaceDefinition_Status2> Status
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((InterfaceDefinition_Status2)(System.Enum.ToObject(typeof(InterfaceDefinition_Status2), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("Status");
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Reason for the status of the Interface
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public System.Nullable<InterfaceDefinition_StatusReason> StatusReason
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
                if ((optionSet != null))
                {
                    return ((InterfaceDefinition_StatusReason)(System.Enum.ToObject(typeof(InterfaceDefinition_StatusReason), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("StatusReason");
                if ((value == null))
                {
                    this.SetAttributeValue("statuscode", null);
                }
                else
                {
                    this.SetAttributeValue("statuscode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("StatusReason");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }

            set
            {
                this.OnPropertyChanging("TimeZoneRuleVersionNumber");
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }

            set
            {
                this.OnPropertyChanging("UTCConversionTimeZoneCode");
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_ActivityPointers
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_ActivityPointers")]
        public System.Collections.Generic.IEnumerable<ActivityPointer> Activities_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ActivityPointer>("mcs_interface_ActivityPointers", null);
            }

            set
            {
                this.OnPropertyChanging("Activities_Regarding");
                this.SetRelatedEntities<ActivityPointer>("mcs_interface_ActivityPointers", null, value);
                this.OnPropertyChanged("Activities_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_Annotations
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_Annotations")]
        public System.Collections.Generic.IEnumerable<Annotation> Notes_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Annotation>("mcs_interface_Annotations", null);
            }

            set
            {
                this.OnPropertyChanging("Notes_Regarding");
                this.SetRelatedEntities<Annotation>("mcs_interface_Annotations", null, value);
                this.OnPropertyChanged("Notes_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_Appointments
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_Appointments")]
        public System.Collections.Generic.IEnumerable<Appointment> ReserveResources_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Appointment>("mcs_interface_Appointments", null);
            }

            set
            {
                this.OnPropertyChanging("ReserveResources_Regarding");
                this.SetRelatedEntities<Appointment>("mcs_interface_Appointments", null, value);
                this.OnPropertyChanged("ReserveResources_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_AsyncOperations
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_AsyncOperations")]
        public System.Collections.Generic.IEnumerable<SystemJob> SystemJobs_Regarding
        {
            get
            {
                return this.GetRelatedEntities<SystemJob>("mcs_interface_AsyncOperations", null);
            }

            set
            {
                this.OnPropertyChanging("SystemJobs_Regarding");
                this.SetRelatedEntities<SystemJob>("mcs_interface_AsyncOperations", null, value);
                this.OnPropertyChanged("SystemJobs_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_BulkDeleteFailures
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_BulkDeleteFailures")]
        public System.Collections.Generic.IEnumerable<BulkDeleteFailure> BulkDeleteFailures_Name
        {
            get
            {
                return this.GetRelatedEntities<BulkDeleteFailure>("mcs_interface_BulkDeleteFailures", null);
            }

            set
            {
                this.OnPropertyChanging("BulkDeleteFailures_Name");
                this.SetRelatedEntities<BulkDeleteFailure>("mcs_interface_BulkDeleteFailures", null, value);
                this.OnPropertyChanged("BulkDeleteFailures_Name");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_connections1
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_connections1")]
        public System.Collections.Generic.IEnumerable<Connection> Connections_ConnectedFrom
        {
            get
            {
                return this.GetRelatedEntities<Connection>("mcs_interface_connections1", null);
            }

            set
            {
                this.OnPropertyChanging("Connections_ConnectedFrom");
                this.SetRelatedEntities<Connection>("mcs_interface_connections1", null, value);
                this.OnPropertyChanged("Connections_ConnectedFrom");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_connections2
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_connections2")]
        public System.Collections.Generic.IEnumerable<Connection> Connections_ConnectedTo
        {
            get
            {
                return this.GetRelatedEntities<Connection>("mcs_interface_connections2", null);
            }

            set
            {
                this.OnPropertyChanging("Connections_ConnectedTo");
                this.SetRelatedEntities<Connection>("mcs_interface_connections2", null, value);
                this.OnPropertyChanged("Connections_ConnectedTo");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_Emails
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_Emails")]
        public System.Collections.Generic.IEnumerable<Email> EmailMessages_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Email>("mcs_interface_Emails", null);
            }

            set
            {
                this.OnPropertyChanging("EmailMessages_Regarding");
                this.SetRelatedEntities<Email>("mcs_interface_Emails", null, value);
                this.OnPropertyChanged("EmailMessages_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_MailboxTrackingFolders
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_MailboxTrackingFolders")]
        public System.Collections.Generic.IEnumerable<MailboxAutoTrackingFolder> MailboxAutoTrackingFolders_RegardingObjectId
        {
            get
            {
                return this.GetRelatedEntities<MailboxAutoTrackingFolder>("mcs_interface_MailboxTrackingFolders", null);
            }

            set
            {
                this.OnPropertyChanging("MailboxAutoTrackingFolders_RegardingObjectId");
                this.SetRelatedEntities<MailboxAutoTrackingFolder>("mcs_interface_MailboxTrackingFolders", null, value);
                this.OnPropertyChanged("MailboxAutoTrackingFolders_RegardingObjectId");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_PrincipalObjectAttributeAccesses
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_PrincipalObjectAttributeAccesses")]
        public System.Collections.Generic.IEnumerable<FieldSharing> FieldSharing_EntityInstance
        {
            get
            {
                return this.GetRelatedEntities<FieldSharing>("mcs_interface_PrincipalObjectAttributeAccesses", null);
            }

            set
            {
                this.OnPropertyChanging("FieldSharing_EntityInstance");
                this.SetRelatedEntities<FieldSharing>("mcs_interface_PrincipalObjectAttributeAccesses", null, value);
                this.OnPropertyChanged("FieldSharing_EntityInstance");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_ProcessSession
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_ProcessSession")]
        public System.Collections.Generic.IEnumerable<ProcessSession> ProcessSessions_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ProcessSession>("mcs_interface_ProcessSession", null);
            }

            set
            {
                this.OnPropertyChanging("ProcessSessions_Regarding");
                this.SetRelatedEntities<ProcessSession>("mcs_interface_ProcessSession", null, value);
                this.OnPropertyChanged("ProcessSessions_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_RecurringAppointmentMasters
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_RecurringAppointmentMasters")]
        public System.Collections.Generic.IEnumerable<RecurringAppointmentMaster> RecurringReserveResources_Regarding
        {
            get
            {
                return this.GetRelatedEntities<RecurringAppointmentMaster>("mcs_interface_RecurringAppointmentMasters", null);
            }

            set
            {
                this.OnPropertyChanging("RecurringReserveResources_Regarding");
                this.SetRelatedEntities<RecurringAppointmentMaster>("mcs_interface_RecurringAppointmentMasters", null, value);
                this.OnPropertyChanged("RecurringReserveResources_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_ServiceAppointments
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_ServiceAppointments")]
        public System.Collections.Generic.IEnumerable<ServiceAppointment> Appointments_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ServiceAppointment>("mcs_interface_ServiceAppointments", null);
            }

            set
            {
                this.OnPropertyChanging("Appointments_Regarding");
                this.SetRelatedEntities<ServiceAppointment>("mcs_interface_ServiceAppointments", null, value);
                this.OnPropertyChanged("Appointments_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_SyncErrors
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_SyncErrors")]
        public System.Collections.Generic.IEnumerable<SyncError> SyncErrors_Record
        {
            get
            {
                return this.GetRelatedEntities<SyncError>("mcs_interface_SyncErrors", null);
            }

            set
            {
                this.OnPropertyChanging("SyncErrors_Record");
                this.SetRelatedEntities<SyncError>("mcs_interface_SyncErrors", null, value);
                this.OnPropertyChanged("SyncErrors_Record");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_Tasks
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_Tasks")]
        public System.Collections.Generic.IEnumerable<Task> Tasks_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Task>("mcs_interface_Tasks", null);
            }

            set
            {
                this.OnPropertyChanging("Tasks_Regarding");
                this.SetRelatedEntities<Task>("mcs_interface_Tasks", null, value);
                this.OnPropertyChanged("Tasks_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_interface_UserEntityInstanceDatas
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_interface_UserEntityInstanceDatas")]
        public System.Collections.Generic.IEnumerable<UserEntityInstanceData> UserEntityInstanceData_ObjectId
        {
            get
            {
                return this.GetRelatedEntities<UserEntityInstanceData>("mcs_interface_UserEntityInstanceDatas", null);
            }

            set
            {
                this.OnPropertyChanging("UserEntityInstanceData_ObjectId");
                this.SetRelatedEntities<UserEntityInstanceData>("mcs_interface_UserEntityInstanceDatas", null, value);
                this.OnPropertyChanged("UserEntityInstanceData_ObjectId");
            }
        }

        /// <summary>
        /// 1:N mcs_mcs_interface_mcs_interfacemessagedirection_interface
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_mcs_interface_mcs_interfacemessagedirection_interface")]
        public System.Collections.Generic.IEnumerable<InterfaceMessageIO> InterfaceMessageIO_Interface
        {
            get
            {
                return this.GetRelatedEntities<InterfaceMessageIO>("mcs_mcs_interface_mcs_interfacemessagedirection_interface", null);
            }

            set
            {
                this.OnPropertyChanging("InterfaceMessageIO_Interface");
                this.SetRelatedEntities<InterfaceMessageIO>("mcs_mcs_interface_mcs_interfacemessagedirection_interface", null, value);
                this.OnPropertyChanged("InterfaceMessageIO_Interface");
            }
        }

        /// <summary>
        /// 1:N mcs_mcs_interface_mcs_interfacemessagetype
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_mcs_interface_mcs_interfacemessagetype")]
        public System.Collections.Generic.IEnumerable<InterfaceMessages> InterfaceMessages_InterfaceID
        {
            get
            {
                return this.GetRelatedEntities<InterfaceMessages>("mcs_mcs_interface_mcs_interfacemessagetype", null);
            }

            set
            {
                this.OnPropertyChanging("InterfaceMessages_InterfaceID");
                this.SetRelatedEntities<InterfaceMessages>("mcs_mcs_interface_mcs_interfacemessagetype", null, value);
                this.OnPropertyChanged("InterfaceMessages_InterfaceID");
            }
        }

        /// <summary>
        /// 1:N mcs_mcs_interface_mcs_interfacesetting
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_mcs_interface_mcs_interfacesetting")]
        public System.Collections.Generic.IEnumerable<InterfaceSettings> InterfaceSettings_InterfaceID
        {
            get
            {
                return this.GetRelatedEntities<InterfaceSettings>("mcs_mcs_interface_mcs_interfacesetting", null);
            }

            set
            {
                this.OnPropertyChanging("InterfaceSettings_InterfaceID");
                this.SetRelatedEntities<InterfaceSettings>("mcs_mcs_interface_mcs_interfacesetting", null, value);
                this.OnPropertyChanged("InterfaceSettings_InterfaceID");
            }
        }

        /// <summary>
        /// 1:N mcs_mcs_interface_mcs_message_exceptioninterface
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_mcs_interface_mcs_message_exceptioninterface")]
        public System.Collections.Generic.IEnumerable<Message> Messages_ExceptionInterface
        {
            get
            {
                return this.GetRelatedEntities<Message>("mcs_mcs_interface_mcs_message_exceptioninterface", null);
            }

            set
            {
                this.OnPropertyChanging("Messages_ExceptionInterface");
                this.SetRelatedEntities<Message>("mcs_mcs_interface_mcs_message_exceptioninterface", null, value);
                this.OnPropertyChanged("Messages_ExceptionInterface");
            }
        }

        /// <summary>
        /// 1:N mcs_mcs_interface_mcs_messagetomessagemapping
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_mcs_interface_mcs_messagetomessagemapping")]
        public System.Collections.Generic.IEnumerable<MessageToMessageTranslation> MessageToMessageTranslation_Interface
        {
            get
            {
                return this.GetRelatedEntities<MessageToMessageTranslation>("mcs_mcs_interface_mcs_messagetomessagemapping", null);
            }

            set
            {
                this.OnPropertyChanging("MessageToMessageTranslation_Interface");
                this.SetRelatedEntities<MessageToMessageTranslation>("mcs_mcs_interface_mcs_messagetomessagemapping", null, value);
                this.OnPropertyChanged("MessageToMessageTranslation_Interface");
            }
        }

        /// <summary>
        /// N:N mcs_mcs_interface_mcs_endpoint
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_mcs_interface_mcs_endpoint")]
        public System.Collections.Generic.IEnumerable<InterfaceEndpoints> InterfaceEndpoints
        {
            get
            {
                return this.GetRelatedEntities<InterfaceEndpoints>("mcs_mcs_interface_mcs_endpoint", null);
            }

            set
            {
                this.OnPropertyChanging("InterfaceEndpoints");
                this.SetRelatedEntities<InterfaceEndpoints>("mcs_mcs_interface_mcs_endpoint", null, value);
                this.OnPropertyChanged("InterfaceEndpoints");
            }
        }

        /// <summary>
        /// N:1 business_unit_mcs_interface
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_mcs_interface")]
        public BusinessUnit InterfaceDefinition_OwningBusinessUnit
        {
            get
            {
                return this.GetRelatedEntity<BusinessUnit>("business_unit_mcs_interface", null);
            }
        }

        /// <summary>
        /// N:1 lk_mcs_interface_createdby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_mcs_interface_createdby")]
        public SystemUser InterfaceDefinition_CreatedBy
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_mcs_interface_createdby", null);
            }
        }

        /// <summary>
        /// N:1 lk_mcs_interface_createdonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_mcs_interface_createdonbehalfby")]
        public SystemUser InterfaceDefinition_CreatedBy_Delegate
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_mcs_interface_createdonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 lk_mcs_interface_modifiedby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_mcs_interface_modifiedby")]
        public SystemUser InterfaceDefinition_ModifiedBy
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_mcs_interface_modifiedby", null);
            }
        }

        /// <summary>
        /// N:1 lk_mcs_interface_modifiedonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_mcs_interface_modifiedonbehalfby")]
        public SystemUser InterfaceDefinition_ModifiedBy_Delegate
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_mcs_interface_modifiedonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 team_mcs_interface
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_mcs_interface")]
        public Team InterfaceDefinition_OwningTeam
        {
            get
            {
                return this.GetRelatedEntity<Team>("team_mcs_interface", null);
            }
        }

        /// <summary>
        /// N:1 user_mcs_interface
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_mcs_interface")]
        public SystemUser InterfaceDefinition_OwningUser
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("user_mcs_interface", null);
            }
        }
    }
}