//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using VA.TMP.DataModel.OptionSets;

namespace VA.TMP.DataModel
{
    /// <summary>
    /// Organizational knowledge for internal and external use.
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("knowledgearticle")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public partial class KnowledgeArticle : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public KnowledgeArticle(): base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "knowledgearticle";
        public const string EntityLogicalCollectionName = "knowledgearticles";
        public const string EntitySetName = "knowledgearticles";
        public const int EntityTypeCode = 9953;
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        private void OnPropertyChanging(string propertyName)
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Shows the automatically generated ID exposed to customers, partners, and other external users to reference and look up articles.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("articlepublicnumber")]
        public string ArticlePublicNumber
        {
            get
            {
                return this.GetAttributeValue<string>("articlepublicnumber");
            }

            set
            {
                this.OnPropertyChanging("ArticlePublicNumber");
                this.SetAttributeValue("articlepublicnumber", value);
                this.OnPropertyChanged("ArticlePublicNumber");
            }
        }

        /// <summary>
        /// Shows the body of the article stored in HTML format.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("content")]
        public string Content
        {
            get
            {
                return this.GetAttributeValue<string>("content");
            }

            set
            {
                this.OnPropertyChanging("Content");
                this.SetAttributeValue("content", value);
                this.OnPropertyChanged("Content");
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy_Delegate
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// A short overview of the article, primarily used in search results and for search engine optimization.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
        public string Description
        {
            get
            {
                return this.GetAttributeValue<string>("description");
            }

            set
            {
                this.OnPropertyChanging("Description");
                this.SetAttributeValue("description", value);
                this.OnPropertyChanged("Description");
            }
        }

        /// <summary>
        /// Exchange rate for the currency associated with the KnowledgeArticle with respect to the base currency.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
        public System.Nullable<decimal> ExchangeRate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
            }
        }

        /// <summary>
        /// Enter an expiration date for the article. Leave this field blank for no expiration date.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("expirationdate")]
        public System.Nullable<System.DateTime> ExpirationDate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("expirationdate");
            }

            set
            {
                this.OnPropertyChanging("ExpirationDate");
                this.SetAttributeValue("expirationdate", value);
                this.OnPropertyChanged("ExpirationDate");
            }
        }

        /// <summary>
        /// Contains the id of the expiration state of the entity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("expirationstateid")]
        public System.Nullable<int> ExpirationStateId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("expirationstateid");
            }

            set
            {
                this.OnPropertyChanging("ExpirationStateId");
                this.SetAttributeValue("expirationstateid", value);
                this.OnPropertyChanged("ExpirationStateId");
            }
        }

        /// <summary>
        /// Contains the id of the expiration status of the entity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("expirationstatusid")]
        public System.Nullable<int> ExpiredStatus
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("expirationstatusid");
            }

            set
            {
                this.OnPropertyChanging("ExpiredStatus");
                this.SetAttributeValue("expirationstatusid", value);
                this.OnPropertyChanged("ExpiredStatus");
            }
        }

        /// <summary>
        /// Expired Review Options
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("expiredreviewoptions")]
        public System.Nullable<KnowledgeArticle_ExpiredReviewOptions> ExpiredReviewOptions
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("expiredreviewoptions");
                if ((optionSet != null))
                {
                    return ((KnowledgeArticle_ExpiredReviewOptions)(System.Enum.ToObject(typeof(KnowledgeArticle_ExpiredReviewOptions), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("ExpiredReviewOptions");
                if ((value == null))
                {
                    this.SetAttributeValue("expiredreviewoptions", null);
                }
                else
                {
                    this.SetAttributeValue("expiredreviewoptions", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("ExpiredReviewOptions");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }

            set
            {
                this.OnPropertyChanging("ImportSequenceNumber");
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Shows whether this article is only visible internally.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isinternal")]
        public System.Nullable<bool> Internal
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("isinternal");
            }

            set
            {
                this.OnPropertyChanging("Internal");
                this.SetAttributeValue("isinternal", value);
                this.OnPropertyChanged("Internal");
            }
        }

        /// <summary>
        /// Shows which version of the knowledge article is the latest version.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("islatestversion")]
        public System.Nullable<bool> IsLatestVersion
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("islatestversion");
            }

            set
            {
                this.OnPropertyChanging("IsLatestVersion");
                this.SetAttributeValue("islatestversion", value);
                this.OnPropertyChanged("IsLatestVersion");
            }
        }

        /// <summary>
        /// Select whether the article is the primary article.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isprimary")]
        public System.Nullable<bool> PrimaryArticle
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("isprimary");
            }

            set
            {
                this.OnPropertyChanging("PrimaryArticle");
                this.SetAttributeValue("isprimary", value);
                this.OnPropertyChanged("PrimaryArticle");
            }
        }

        /// <summary>
        /// Select whether the article is the root article.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isrootarticle")]
        public System.Nullable<bool> RootArticle
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("isrootarticle");
            }

            set
            {
                this.OnPropertyChanging("RootArticle");
                this.SetAttributeValue("isrootarticle", value);
                this.OnPropertyChanged("RootArticle");
            }
        }

        /// <summary>
        /// Type keywords to be used for searches in knowledge base articles. Separate keywords by using commas.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("keywords")]
        public string Keywords
        {
            get
            {
                return this.GetAttributeValue<string>("keywords");
            }

            set
            {
                this.OnPropertyChanging("Keywords");
                this.SetAttributeValue("keywords", value);
                this.OnPropertyChanged("Keywords");
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("knowledgearticleid")]
        public System.Nullable<System.Guid> KnowledgeArticleId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("knowledgearticleid");
            }

            set
            {
                this.OnPropertyChanging("KnowledgeArticleId");
                this.SetAttributeValue("knowledgearticleid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }

                this.OnPropertyChanged("KnowledgeArticleId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("knowledgearticleid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }

            set
            {
                this.KnowledgeArticleId = value;
            }
        }

        /// <summary>
        /// Shows the total number of article views.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("knowledgearticleviews")]
        public System.Nullable<int> KnowledgeArticleViews
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("knowledgearticleviews");
            }
        }

        /// <summary>
        /// The date time for Knowledge Article View.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("knowledgearticleviews_date")]
        public System.Nullable<System.DateTime> KnowledgeArticleView_LastUpdatedTime
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("knowledgearticleviews_date");
            }
        }

        /// <summary>
        /// State of Knowledge Article View.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("knowledgearticleviews_state")]
        public System.Nullable<int> KnowledgeArticleView_State
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("knowledgearticleviews_state");
            }
        }

        /// <summary>
        /// Select the language that the article's content is in.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("languagelocaleid")]
        public Microsoft.Xrm.Sdk.EntityReference Language
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("languagelocaleid");
            }

            set
            {
                this.OnPropertyChanging("Language");
                this.SetAttributeValue("languagelocaleid", value);
                this.OnPropertyChanged("Language");
            }
        }

        /// <summary>
        /// Shows the major version number of this article's content.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("majorversionnumber")]
        public System.Nullable<int> MajorVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("majorversionnumber");
            }

            set
            {
                this.OnPropertyChanging("MajorVersionNumber");
                this.SetAttributeValue("majorversionnumber", value);
                this.OnPropertyChanged("MajorVersionNumber");
            }
        }

        /// <summary>
        /// Shows the minor version number of this article's content.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("minorversionnumber")]
        public System.Nullable<int> MinorVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("minorversionnumber");
            }

            set
            {
                this.OnPropertyChanging("MinorVersionNumber");
                this.SetAttributeValue("minorversionnumber", value);
                this.OnPropertyChanged("MinorVersionNumber");
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy_Delegate
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Stores the reference to content in file store
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_contentstore")]
        public object FileStorageContentReference
        {
            get
            {
                return this.GetAttributeValue<object>("msdyn_contentstore");
            }
        }

        /// <summary>
        /// Ingested article URL
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_ingestedarticleurl")]
        public string IngestedArticleURL
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_ingestedarticleurl");
            }

            set
            {
                this.OnPropertyChanging("IngestedArticleURL");
                this.SetAttributeValue("msdyn_ingestedarticleurl", value);
                this.OnPropertyChanged("IngestedArticleURL");
            }
        }

        /// <summary>
        /// Sets whether the article content is synced to file storage
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_iscontentsyncedtostore")]
        public System.Nullable<bool> IsContentSyncedToFileStorage
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_iscontentsyncedtostore");
            }

            set
            {
                this.OnPropertyChanging("IsContentSyncedToFileStorage");
                this.SetAttributeValue("msdyn_iscontentsyncedtostore", value);
                this.OnPropertyChanged("IsContentSyncedToFileStorage");
            }
        }

        /// <summary>
        /// Value is true for all Ingested articles
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_isingestedarticle")]
        public System.Nullable<bool> IsIngestedArticle
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_isingestedarticle");
            }

            set
            {
                this.OnPropertyChanging("IsIngestedArticle");
                this.SetAttributeValue("msdyn_isingestedarticle", value);
                this.OnPropertyChanged("IsIngestedArticle");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_keywordsdescsuggestioncontrol")]
        public System.Nullable<bool> KeywordsAndDescriptionSuggestionControl
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("msdyn_keywordsdescsuggestioncontrol");
            }

            set
            {
                this.OnPropertyChanging("KeywordsAndDescriptionSuggestionControl");
                this.SetAttributeValue("msdyn_keywordsdescsuggestioncontrol", value);
                this.OnPropertyChanged("KeywordsAndDescriptionSuggestionControl");
            }
        }

        /// <summary>
        /// Displays the number of times migration to file storage retry is attempted for an article
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_retrycountformigrationtocontentstore")]
        public System.Nullable<int> FileStorageMigrationRetryCount
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("msdyn_retrycountformigrationtocontentstore");
            }

            set
            {
                this.OnPropertyChanging("FileStorageMigrationRetryCount");
                this.SetAttributeValue("msdyn_retrycountformigrationtocontentstore", value);
                this.OnPropertyChanged("FileStorageMigrationRetryCount");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> RecordCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }

            set
            {
                this.OnPropertyChanging("RecordCreatedOn");
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("RecordCreatedOn");
            }
        }

        /// <summary>
        /// Unique identifier of the user or team who owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference Owner
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }

            set
            {
                this.OnPropertyChanging("Owner");
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("Owner");
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Contains the id of the parent article content associated with the entity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentarticlecontentid")]
        public Microsoft.Xrm.Sdk.EntityReference ParentArticleContentId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentarticlecontentid");
            }

            set
            {
                this.OnPropertyChanging("ParentArticleContentId");
                this.SetAttributeValue("parentarticlecontentid", value);
                this.OnPropertyChanged("ParentArticleContentId");
            }
        }

        /// <summary>
        /// Shows the version that the current article was restored from.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("previousarticlecontentid")]
        public Microsoft.Xrm.Sdk.EntityReference PreviousArticleContentID
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("previousarticlecontentid");
            }

            set
            {
                this.OnPropertyChanging("PreviousArticleContentID");
                this.SetAttributeValue("previousarticlecontentid", value);
                this.OnPropertyChanged("PreviousArticleContentID");
            }
        }

        /// <summary>
        /// Contains the id of the primary author associated with the article.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primaryauthorid")]
        public Microsoft.Xrm.Sdk.EntityReference PrimaryAuthorId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("primaryauthorid");
            }

            set
            {
                this.OnPropertyChanging("PrimaryAuthorId");
                this.SetAttributeValue("primaryauthorid", value);
                this.OnPropertyChanged("PrimaryAuthorId");
            }
        }

        /// <summary>
        /// Contains the id of the process associated with the entity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
        public System.Nullable<System.Guid> ProcessId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
            }

            set
            {
                this.OnPropertyChanging("ProcessId");
                this.SetAttributeValue("processid", value);
                this.OnPropertyChanged("ProcessId");
            }
        }

        /// <summary>
        /// Date and time when the record was published.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("publishon")]
        public System.Nullable<System.DateTime> PublishOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("publishon");
            }

            set
            {
                this.OnPropertyChanging("PublishOn");
                this.SetAttributeValue("publishon", value);
                this.OnPropertyChanged("PublishOn");
            }
        }

        /// <summary>
        /// Publish Status of the Article.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("publishstatusid")]
        public System.Nullable<int> PublishedStatus
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("publishstatusid");
            }

            set
            {
                this.OnPropertyChanging("PublishedStatus");
                this.SetAttributeValue("publishstatusid", value);
                this.OnPropertyChanged("PublishedStatus");
            }
        }

        /// <summary>
        /// Information which specifies how helpful the related record was.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rating")]
        public System.Nullable<decimal> Rating
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("rating");
            }
        }

        /// <summary>
        /// Rating Count
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rating_count")]
        public System.Nullable<int> Rating_Count
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("rating_count");
            }
        }

        /// <summary>
        /// The date time for Rating.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rating_date")]
        public System.Nullable<System.DateTime> Rating_LastUpdatedTime
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("rating_date");
            }
        }

        /// <summary>
        /// State of Rating
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rating_state")]
        public System.Nullable<int> Rating_State
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("rating_state");
            }
        }

        /// <summary>
        /// Total sum of Rating
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rating_sum")]
        public System.Nullable<decimal> Rating_sum
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("rating_sum");
            }
        }

        /// <summary>
        /// Ready For Review
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("readyforreview")]
        public System.Nullable<bool> ReadyForReview
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("readyforreview");
            }

            set
            {
                this.OnPropertyChanging("ReadyForReview");
                this.SetAttributeValue("readyforreview", value);
                this.OnPropertyChanged("ReadyForReview");
            }
        }

        /// <summary>
        /// Review
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("review")]
        public System.Nullable<KnowledgeArticle_Review> Review
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("review");
                if ((optionSet != null))
                {
                    return ((KnowledgeArticle_Review)(System.Enum.ToObject(typeof(KnowledgeArticle_Review), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("Review");
                if ((value == null))
                {
                    this.SetAttributeValue("review", null);
                }
                else
                {
                    this.SetAttributeValue("review", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("Review");
            }
        }

        /// <summary>
        /// Contains the id of the root article.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rootarticleid")]
        public Microsoft.Xrm.Sdk.EntityReference RootArticleId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("rootarticleid");
            }

            set
            {
                this.OnPropertyChanging("RootArticleId");
                this.SetAttributeValue("rootarticleid", value);
                this.OnPropertyChanged("RootArticleId");
            }
        }

        /// <summary>
        /// Contains the id of the scheduled status of the entity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("scheduledstatusid")]
        public System.Nullable<int> ScheduledStatus
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("scheduledstatusid");
            }

            set
            {
                this.OnPropertyChanging("ScheduledStatus");
                this.SetAttributeValue("scheduledstatusid", value);
                this.OnPropertyChanged("ScheduledStatus");
            }
        }

        /// <summary>
        /// Shows whether category associations have been set
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("setcategoryassociations")]
        public System.Nullable<bool> SetCategoryAssociations
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("setcategoryassociations");
            }

            set
            {
                this.OnPropertyChanging("SetCategoryAssociations");
                this.SetAttributeValue("setcategoryassociations", value);
                this.OnPropertyChanged("SetCategoryAssociations");
            }
        }

        /// <summary>
        /// Set Product Associations
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("setproductassociations")]
        public System.Nullable<bool> SetProductAssociations
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("setproductassociations");
            }

            set
            {
                this.OnPropertyChanging("SetProductAssociations");
                this.SetAttributeValue("setproductassociations", value);
                this.OnPropertyChanged("SetProductAssociations");
            }
        }

        /// <summary>
        /// Contains the id of the stage where the entity is located.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
        public System.Nullable<System.Guid> StageId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
            }

            set
            {
                this.OnPropertyChanging("StageId");
                this.SetAttributeValue("stageid", value);
                this.OnPropertyChanged("StageId");
            }
        }

        /// <summary>
        /// Shows whether the article is a draft or is published, archived, or discarded. Draft articles aren't available externally and can be edited. Published articles are available externally, based on applicable permissions, but can't be edited. All metadata changes are reflected in the published version. Archived and discarded articles aren't available externally and can't be edited.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public System.Nullable<KnowledgeArticle_Status> Status
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((KnowledgeArticle_Status)(System.Enum.ToObject(typeof(KnowledgeArticle_Status), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("Status");
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Select the article's status.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public System.Nullable<KnowledgeArticle_StatusReason> StatusReason
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
                if ((optionSet != null))
                {
                    return ((KnowledgeArticle_StatusReason)(System.Enum.ToObject(typeof(KnowledgeArticle_StatusReason), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("StatusReason");
                if ((value == null))
                {
                    this.SetAttributeValue("statuscode", null);
                }
                else
                {
                    this.SetAttributeValue("statuscode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("StatusReason");
            }
        }

        /// <summary>
        /// Choose the subject of the article to assist with article searches. You can configure subjects under Business Management in the Settings area.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subjectid")]
        public Microsoft.Xrm.Sdk.EntityReference Subject
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("subjectid");
            }

            set
            {
                this.OnPropertyChanging("Subject");
                this.SetAttributeValue("subjectid", value);
                this.OnPropertyChanged("Subject");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }

            set
            {
                this.OnPropertyChanging("TimeZoneRuleVersionNumber");
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Type a title for the article.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("title")]
        public string Title
        {
            get
            {
                return this.GetAttributeValue<string>("title");
            }

            set
            {
                this.OnPropertyChanging("Title");
                this.SetAttributeValue("title", value);
                this.OnPropertyChanged("Title");
            }
        }

        /// <summary>
        /// Exchange rate for the currency associated with the KnowledgeArticle with respect to the base currency.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
        public Microsoft.Xrm.Sdk.EntityReference Currency
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
            }

            set
            {
                this.OnPropertyChanging("Currency");
                this.SetAttributeValue("transactioncurrencyid", value);
                this.OnPropertyChanged("Currency");
            }
        }

        /// <summary>
        /// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
        public string _Deprecated_TraversedPath
        {
            get
            {
                return this.GetAttributeValue<string>("traversedpath");
            }

            set
            {
                this.OnPropertyChanging("_Deprecated_TraversedPath");
                this.SetAttributeValue("traversedpath", value);
                this.OnPropertyChanged("_Deprecated_TraversedPath");
            }
        }

        /// <summary>
        /// Update Content
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("updatecontent")]
        public System.Nullable<bool> UpdateContent
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("updatecontent");
            }

            set
            {
                this.OnPropertyChanging("UpdateContent");
                this.SetAttributeValue("updatecontent", value);
                this.OnPropertyChanged("UpdateContent");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }

            set
            {
                this.OnPropertyChanging("UTCConversionTimeZoneCode");
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_activity_parties
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_activity_parties")]
        public System.Collections.Generic.IEnumerable<ActivityParty> ActivityParties_Party
        {
            get
            {
                return this.GetRelatedEntities<ActivityParty>("knowledgearticle_activity_parties", null);
            }

            set
            {
                this.OnPropertyChanging("ActivityParties_Party");
                this.SetRelatedEntities<ActivityParty>("knowledgearticle_activity_parties", null, value);
                this.OnPropertyChanged("ActivityParties_Party");
            }
        }

        /// <summary>
        /// 1:N KnowledgeArticle_ActivityPointers
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeArticle_ActivityPointers")]
        public System.Collections.Generic.IEnumerable<ActivityPointer> Activities_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ActivityPointer>("KnowledgeArticle_ActivityPointers", null);
            }

            set
            {
                this.OnPropertyChanging("Activities_Regarding");
                this.SetRelatedEntities<ActivityPointer>("KnowledgeArticle_ActivityPointers", null, value);
                this.OnPropertyChanged("Activities_Regarding");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_Annotations
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_Annotations")]
        public System.Collections.Generic.IEnumerable<Annotation> Notes_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Annotation>("knowledgearticle_Annotations", null);
            }

            set
            {
                this.OnPropertyChanging("Notes_Regarding");
                this.SetRelatedEntities<Annotation>("knowledgearticle_Annotations", null, value);
                this.OnPropertyChanged("Notes_Regarding");
            }
        }

        /// <summary>
        /// 1:N KnowledgeArticle_Appointments
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeArticle_Appointments")]
        public System.Collections.Generic.IEnumerable<Appointment> ReserveResources_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Appointment>("KnowledgeArticle_Appointments", null);
            }

            set
            {
                this.OnPropertyChanging("ReserveResources_Regarding");
                this.SetRelatedEntities<Appointment>("KnowledgeArticle_Appointments", null, value);
                this.OnPropertyChanged("ReserveResources_Regarding");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_AsyncOperations
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_AsyncOperations")]
        public System.Collections.Generic.IEnumerable<SystemJob> SystemJobs_Regarding
        {
            get
            {
                return this.GetRelatedEntities<SystemJob>("knowledgearticle_AsyncOperations", null);
            }

            set
            {
                this.OnPropertyChanging("SystemJobs_Regarding");
                this.SetRelatedEntities<SystemJob>("knowledgearticle_AsyncOperations", null, value);
                this.OnPropertyChanged("SystemJobs_Regarding");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_BulkDeleteFailures
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_BulkDeleteFailures")]
        public System.Collections.Generic.IEnumerable<BulkDeleteFailure> BulkDeleteFailures_Name
        {
            get
            {
                return this.GetRelatedEntities<BulkDeleteFailure>("knowledgearticle_BulkDeleteFailures", null);
            }

            set
            {
                this.OnPropertyChanging("BulkDeleteFailures_Name");
                this.SetRelatedEntities<BulkDeleteFailure>("knowledgearticle_BulkDeleteFailures", null, value);
                this.OnPropertyChanged("BulkDeleteFailures_Name");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_BulkOperations
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_BulkOperations")]
        public System.Collections.Generic.IEnumerable<QuickCampaign> QuickCampaigns_ImportFileName
        {
            get
            {
                return this.GetRelatedEntities<QuickCampaign>("knowledgearticle_BulkOperations", null);
            }

            set
            {
                this.OnPropertyChanging("QuickCampaigns_ImportFileName");
                this.SetRelatedEntities<QuickCampaign>("knowledgearticle_BulkOperations", null, value);
                this.OnPropertyChanged("QuickCampaigns_ImportFileName");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_CampaignResponses
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_CampaignResponses")]
        public System.Collections.Generic.IEnumerable<CampaignResponse> CampaignResponses_ParentCampaign
        {
            get
            {
                return this.GetRelatedEntities<CampaignResponse>("knowledgearticle_CampaignResponses", null);
            }

            set
            {
                this.OnPropertyChanging("CampaignResponses_ParentCampaign");
                this.SetRelatedEntities<CampaignResponse>("knowledgearticle_CampaignResponses", null, value);
                this.OnPropertyChanged("CampaignResponses_ParentCampaign");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_connections1
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_connections1")]
        public System.Collections.Generic.IEnumerable<Connection> Connections_ConnectedFrom
        {
            get
            {
                return this.GetRelatedEntities<Connection>("knowledgearticle_connections1", null);
            }

            set
            {
                this.OnPropertyChanging("Connections_ConnectedFrom");
                this.SetRelatedEntities<Connection>("knowledgearticle_connections1", null, value);
                this.OnPropertyChanged("Connections_ConnectedFrom");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_connections2
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_connections2")]
        public System.Collections.Generic.IEnumerable<Connection> Connections_ConnectedTo
        {
            get
            {
                return this.GetRelatedEntities<Connection>("knowledgearticle_connections2", null);
            }

            set
            {
                this.OnPropertyChanging("Connections_ConnectedTo");
                this.SetRelatedEntities<Connection>("knowledgearticle_connections2", null, value);
                this.OnPropertyChanged("Connections_ConnectedTo");
            }
        }

        /// <summary>
        /// 1:N KnowledgeArticle_Emails
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeArticle_Emails")]
        public System.Collections.Generic.IEnumerable<Email> EmailMessages_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Email>("KnowledgeArticle_Emails", null);
            }

            set
            {
                this.OnPropertyChanging("EmailMessages_Regarding");
                this.SetRelatedEntities<Email>("KnowledgeArticle_Emails", null, value);
                this.OnPropertyChanged("EmailMessages_Regarding");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_parentarticle_contentid
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_parentarticle_contentid", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
        public System.Collections.Generic.IEnumerable<KnowledgeArticle> KnowledgeArticles_ParentArticleContentId_Referenced
        {
            get
            {
                return this.GetRelatedEntities<KnowledgeArticle>("knowledgearticle_parentarticle_contentid", Microsoft.Xrm.Sdk.EntityRole.Referenced);
            }

            set
            {
                this.OnPropertyChanging("KnowledgeArticles_ParentArticleContentId_Referenced");
                this.SetRelatedEntities<KnowledgeArticle>("knowledgearticle_parentarticle_contentid", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
                this.OnPropertyChanged("KnowledgeArticles_ParentArticleContentId_Referenced");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_previousarticle_contentid
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_previousarticle_contentid", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
        public System.Collections.Generic.IEnumerable<KnowledgeArticle> KnowledgeArticles_PreviousArticleContentID_Referenced
        {
            get
            {
                return this.GetRelatedEntities<KnowledgeArticle>("knowledgearticle_previousarticle_contentid", Microsoft.Xrm.Sdk.EntityRole.Referenced);
            }

            set
            {
                this.OnPropertyChanging("KnowledgeArticles_PreviousArticleContentID_Referenced");
                this.SetRelatedEntities<KnowledgeArticle>("knowledgearticle_previousarticle_contentid", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
                this.OnPropertyChanged("KnowledgeArticles_PreviousArticleContentID_Referenced");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_PrincipalObjectAttributeAccess
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_PrincipalObjectAttributeAccess")]
        public System.Collections.Generic.IEnumerable<FieldSharing> FieldSharing_EntityInstance
        {
            get
            {
                return this.GetRelatedEntities<FieldSharing>("knowledgearticle_PrincipalObjectAttributeAccess", null);
            }

            set
            {
                this.OnPropertyChanging("FieldSharing_EntityInstance");
                this.SetRelatedEntities<FieldSharing>("knowledgearticle_PrincipalObjectAttributeAccess", null, value);
                this.OnPropertyChanged("FieldSharing_EntityInstance");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_ProcessSession
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_ProcessSession")]
        public System.Collections.Generic.IEnumerable<ProcessSession> ProcessSessions_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ProcessSession>("knowledgearticle_ProcessSession", null);
            }

            set
            {
                this.OnPropertyChanging("ProcessSessions_Regarding");
                this.SetRelatedEntities<ProcessSession>("knowledgearticle_ProcessSession", null, value);
                this.OnPropertyChanged("ProcessSessions_Regarding");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_QueueItems
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_QueueItems")]
        public System.Collections.Generic.IEnumerable<QueueItem> QueueItems_Object
        {
            get
            {
                return this.GetRelatedEntities<QueueItem>("knowledgearticle_QueueItems", null);
            }

            set
            {
                this.OnPropertyChanging("QueueItems_Object");
                this.SetRelatedEntities<QueueItem>("knowledgearticle_QueueItems", null, value);
                this.OnPropertyChanged("QueueItems_Object");
            }
        }

        /// <summary>
        /// 1:N KnowledgeArticle_RecurringAppointmentMasters
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeArticle_RecurringAppointmentMasters")]
        public System.Collections.Generic.IEnumerable<RecurringAppointmentMaster> RecurringReserveResources_Regarding
        {
            get
            {
                return this.GetRelatedEntities<RecurringAppointmentMaster>("KnowledgeArticle_RecurringAppointmentMasters", null);
            }

            set
            {
                this.OnPropertyChanging("RecurringReserveResources_Regarding");
                this.SetRelatedEntities<RecurringAppointmentMaster>("KnowledgeArticle_RecurringAppointmentMasters", null, value);
                this.OnPropertyChanged("RecurringReserveResources_Regarding");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_rootarticle_id
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_rootarticle_id", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
        public System.Collections.Generic.IEnumerable<KnowledgeArticle> KnowledgeArticles_RootArticleId_Referenced
        {
            get
            {
                return this.GetRelatedEntities<KnowledgeArticle>("knowledgearticle_rootarticle_id", Microsoft.Xrm.Sdk.EntityRole.Referenced);
            }

            set
            {
                this.OnPropertyChanging("KnowledgeArticles_RootArticleId_Referenced");
                this.SetRelatedEntities<KnowledgeArticle>("knowledgearticle_rootarticle_id", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
                this.OnPropertyChanged("KnowledgeArticles_RootArticleId_Referenced");
            }
        }

        /// <summary>
        /// 1:N KnowledgeArticle_ServiceAppointments
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeArticle_ServiceAppointments")]
        public System.Collections.Generic.IEnumerable<ServiceAppointment> Appointments_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ServiceAppointment>("KnowledgeArticle_ServiceAppointments", null);
            }

            set
            {
                this.OnPropertyChanging("Appointments_Regarding");
                this.SetRelatedEntities<ServiceAppointment>("KnowledgeArticle_ServiceAppointments", null, value);
                this.OnPropertyChanged("Appointments_Regarding");
            }
        }

        /// <summary>
        /// 1:N KnowledgeArticle_SyncErrors
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeArticle_SyncErrors")]
        public System.Collections.Generic.IEnumerable<SyncError> SyncErrors_Record
        {
            get
            {
                return this.GetRelatedEntities<SyncError>("KnowledgeArticle_SyncErrors", null);
            }

            set
            {
                this.OnPropertyChanging("SyncErrors_Record");
                this.SetRelatedEntities<SyncError>("KnowledgeArticle_SyncErrors", null, value);
                this.OnPropertyChanged("SyncErrors_Record");
            }
        }

        /// <summary>
        /// 1:N KnowledgeArticle_Tasks
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("KnowledgeArticle_Tasks")]
        public System.Collections.Generic.IEnumerable<Task> Tasks_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Task>("KnowledgeArticle_Tasks", null);
            }

            set
            {
                this.OnPropertyChanging("Tasks_Regarding");
                this.SetRelatedEntities<Task>("KnowledgeArticle_Tasks", null, value);
                this.OnPropertyChanged("Tasks_Regarding");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_Teams
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_Teams")]
        public System.Collections.Generic.IEnumerable<Team> Teams_RegardingObjectId
        {
            get
            {
                return this.GetRelatedEntities<Team>("knowledgearticle_Teams", null);
            }

            set
            {
                this.OnPropertyChanging("Teams_RegardingObjectId");
                this.SetRelatedEntities<Team>("knowledgearticle_Teams", null, value);
                this.OnPropertyChanged("Teams_RegardingObjectId");
            }
        }

        /// <summary>
        /// 1:N knowledgearticle_UserEntityInstanceDatas
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_UserEntityInstanceDatas")]
        public System.Collections.Generic.IEnumerable<UserEntityInstanceData> UserEntityInstanceData_ObjectId
        {
            get
            {
                return this.GetRelatedEntities<UserEntityInstanceData>("knowledgearticle_UserEntityInstanceDatas", null);
            }

            set
            {
                this.OnPropertyChanging("UserEntityInstanceData_ObjectId");
                this.SetRelatedEntities<UserEntityInstanceData>("knowledgearticle_UserEntityInstanceDatas", null, value);
                this.OnPropertyChanged("UserEntityInstanceData_ObjectId");
            }
        }

        /// <summary>
        /// N:N msdyn_msdyn_customerasset_knowledgearticle
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_customerasset_knowledgearticle")]
        public System.Collections.Generic.IEnumerable<CustomerAsset> CustomerAssets
        {
            get
            {
                return this.GetRelatedEntities<CustomerAsset>("msdyn_msdyn_customerasset_knowledgearticle", null);
            }

            set
            {
                this.OnPropertyChanging("CustomerAssets");
                this.SetRelatedEntities<CustomerAsset>("msdyn_msdyn_customerasset_knowledgearticle", null, value);
                this.OnPropertyChanged("CustomerAssets");
            }
        }

        /// <summary>
        /// N:1 business_unit_knowledgearticle
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_knowledgearticle")]
        public BusinessUnit KnowledgeArticles_OwningBusinessUnit
        {
            get
            {
                return this.GetRelatedEntity<BusinessUnit>("business_unit_knowledgearticle", null);
            }
        }

        /// <summary>
        /// N:1 knowledgearticle_parentarticle_contentid
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentarticlecontentid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_parentarticle_contentid", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
        public KnowledgeArticle KnowledgeArticles_ParentArticleContentId_Referencing
        {
            get
            {
                return this.GetRelatedEntity<KnowledgeArticle>("knowledgearticle_parentarticle_contentid", Microsoft.Xrm.Sdk.EntityRole.Referencing);
            }

            set
            {
                this.OnPropertyChanging("KnowledgeArticles_ParentArticleContentId_Referencing");
                this.SetRelatedEntity<KnowledgeArticle>("knowledgearticle_parentarticle_contentid", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
                this.OnPropertyChanged("KnowledgeArticles_ParentArticleContentId_Referencing");
            }
        }

        /// <summary>
        /// N:1 knowledgearticle_previousarticle_contentid
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("previousarticlecontentid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_previousarticle_contentid", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
        public KnowledgeArticle KnowledgeArticles_PreviousArticleContentID_Referencing
        {
            get
            {
                return this.GetRelatedEntity<KnowledgeArticle>("knowledgearticle_previousarticle_contentid", Microsoft.Xrm.Sdk.EntityRole.Referencing);
            }

            set
            {
                this.OnPropertyChanging("KnowledgeArticles_PreviousArticleContentID_Referencing");
                this.SetRelatedEntity<KnowledgeArticle>("knowledgearticle_previousarticle_contentid", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
                this.OnPropertyChanged("KnowledgeArticles_PreviousArticleContentID_Referencing");
            }
        }

        /// <summary>
        /// N:1 knowledgearticle_primaryauthorid
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primaryauthorid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_primaryauthorid")]
        public SystemUser KnowledgeArticles_PrimaryAuthorId
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("knowledgearticle_primaryauthorid", null);
            }

            set
            {
                this.OnPropertyChanging("KnowledgeArticles_PrimaryAuthorId");
                this.SetRelatedEntity<SystemUser>("knowledgearticle_primaryauthorid", null, value);
                this.OnPropertyChanged("KnowledgeArticles_PrimaryAuthorId");
            }
        }

        /// <summary>
        /// N:1 knowledgearticle_rootarticle_id
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("rootarticleid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("knowledgearticle_rootarticle_id", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
        public KnowledgeArticle KnowledgeArticles_RootArticleId_Referencing
        {
            get
            {
                return this.GetRelatedEntity<KnowledgeArticle>("knowledgearticle_rootarticle_id", Microsoft.Xrm.Sdk.EntityRole.Referencing);
            }

            set
            {
                this.OnPropertyChanging("KnowledgeArticles_RootArticleId_Referencing");
                this.SetRelatedEntity<KnowledgeArticle>("knowledgearticle_rootarticle_id", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
                this.OnPropertyChanged("KnowledgeArticles_RootArticleId_Referencing");
            }
        }

        /// <summary>
        /// N:1 lk_knowledgearticle_createdby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_knowledgearticle_createdby")]
        public SystemUser KnowledgeArticles_CreatedBy
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_knowledgearticle_createdby", null);
            }
        }

        /// <summary>
        /// N:1 lk_knowledgearticle_createdonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_knowledgearticle_createdonbehalfby")]
        public SystemUser KnowledgeArticles_CreatedBy_Delegate
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_knowledgearticle_createdonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 lk_knowledgearticle_modifiedby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_knowledgearticle_modifiedby")]
        public SystemUser KnowledgeArticles_ModifiedBy
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_knowledgearticle_modifiedby", null);
            }
        }

        /// <summary>
        /// N:1 lk_knowledgearticle_modifiedonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_knowledgearticle_modifiedonbehalfby")]
        public SystemUser KnowledgeArticles_ModifiedBy_Delegate
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_knowledgearticle_modifiedonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 team_knowledgearticle
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_knowledgearticle")]
        public Team KnowledgeArticles_OwningTeam
        {
            get
            {
                return this.GetRelatedEntity<Team>("team_knowledgearticle", null);
            }
        }

        /// <summary>
        /// N:1 TransactionCurrency_knowledgearticle
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_knowledgearticle")]
        public Currency KnowledgeArticles_Currency
        {
            get
            {
                return this.GetRelatedEntity<Currency>("TransactionCurrency_knowledgearticle", null);
            }

            set
            {
                this.OnPropertyChanging("KnowledgeArticles_Currency");
                this.SetRelatedEntity<Currency>("TransactionCurrency_knowledgearticle", null, value);
                this.OnPropertyChanged("KnowledgeArticles_Currency");
            }
        }

        /// <summary>
        /// N:1 user_knowledgearticle
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_knowledgearticle")]
        public SystemUser KnowledgeArticles_OwningUser
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("user_knowledgearticle", null);
            }
        }
    }
}