//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VA.TMP.OptionSets;

namespace VA.TMP.DataModel
{
    /// <summary>
    /// Telehealth Service Agreements
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("mcs_services")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public partial class mcs_services : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public mcs_services(): base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "mcs_services";
        public const string EntityLogicalCollectionName = "mcs_serviceses";
        public const string EntitySetName = "mcs_serviceses";
        public const int EntityTypeCode = 10012;
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        private void OnPropertyChanging(string propertyName)
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_addresources")]
        public System.Nullable<bool> cvt_addresources
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("cvt_addresources");
            }

            set
            {
                this.OnPropertyChanging("cvt_addresources");
                this.SetAttributeValue("cvt_addresources", value);
                this.OnPropertyChanged("cvt_addresources");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_availabletelehealthmodalities")]
        public System.Nullable<mcs_servicescvt_AvailableTelehealthModalities> cvt_AvailableTelehealthModalities
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("cvt_availabletelehealthmodalities");
                if ((optionSet != null))
                {
                    return ((mcs_servicescvt_AvailableTelehealthModalities)(System.Enum.ToObject(typeof(mcs_servicescvt_AvailableTelehealthModalities), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("cvt_AvailableTelehealthModalities");
                if ((value == null))
                {
                    this.SetAttributeValue("cvt_availabletelehealthmodalities", null);
                }
                else
                {
                    this.SetAttributeValue("cvt_availabletelehealthmodalities", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("cvt_AvailableTelehealthModalities");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_beginngtime")]
        public System.Nullable<System.DateTime> cvt_beginngtime
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("cvt_beginngtime");
            }

            set
            {
                this.OnPropertyChanging("cvt_beginngtime");
                this.SetAttributeValue("cvt_beginngtime", value);
                this.OnPropertyChanged("cvt_beginngtime");
            }
        }

        /// <summary>
        /// Unique identifier for TMP Resource associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_bulkaddresource")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_BulkAddResource
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_bulkaddresource");
            }

            set
            {
                this.OnPropertyChanging("cvt_BulkAddResource");
                this.SetAttributeValue("cvt_bulkaddresource", value);
                this.OnPropertyChanged("cvt_BulkAddResource");
            }
        }

        /// <summary>
        /// Unique identifier for TSS Resource Group associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_bulkaddresourcegroup")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_BulkAddResourceGroup
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_bulkaddresourcegroup");
            }

            set
            {
                this.OnPropertyChanging("cvt_BulkAddResourceGroup");
                this.SetAttributeValue("cvt_bulkaddresourcegroup", value);
                this.OnPropertyChanged("cvt_BulkAddResourceGroup");
            }
        }

        /// <summary>
        /// Unique identifier for Resource: User associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_bulkadduser")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_BulkAddUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_bulkadduser");
            }

            set
            {
                this.OnPropertyChanging("cvt_BulkAddUser");
                this.SetAttributeValue("cvt_bulkadduser", value);
                this.OnPropertyChanged("cvt_BulkAddUser");
            }
        }

        /// <summary>
        /// Unique identifier for TMP Resource associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_bulkremoveresource")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_BulkRemoveResource
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_bulkremoveresource");
            }

            set
            {
                this.OnPropertyChanging("cvt_BulkRemoveResource");
                this.SetAttributeValue("cvt_bulkremoveresource", value);
                this.OnPropertyChanged("cvt_BulkRemoveResource");
            }
        }

        /// <summary>
        /// Unique identifier for TSS Resource Group associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_bulkremoveresourcegroup")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_BulkRemoveResourceGroup
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_bulkremoveresourcegroup");
            }

            set
            {
                this.OnPropertyChanging("cvt_BulkRemoveResourceGroup");
                this.SetAttributeValue("cvt_bulkremoveresourcegroup", value);
                this.OnPropertyChanged("cvt_BulkRemoveResourceGroup");
            }
        }

        /// <summary>
        /// Unique identifier for Resource: User associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_bulkremoveuser")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_BulkRemoveUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_bulkremoveuser");
            }

            set
            {
                this.OnPropertyChanging("cvt_BulkRemoveUser");
                this.SetAttributeValue("cvt_bulkremoveuser", value);
                this.OnPropertyChanged("cvt_BulkRemoveUser");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_duration")]
        public System.Nullable<int> cvt_duration
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("cvt_duration");
            }

            set
            {
                this.OnPropertyChanging("cvt_duration");
                this.SetAttributeValue("cvt_duration", value);
                this.OnPropertyChanged("cvt_duration");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_groupappointment")]
        public System.Nullable<bool> cvt_groupappointment
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("cvt_groupappointment");
            }

            set
            {
                this.OnPropertyChanging("cvt_groupappointment");
                this.SetAttributeValue("cvt_groupappointment", value);
                this.OnPropertyChanged("cvt_groupappointment");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_grouppatientbranch")]
        public string cvt_grouppatientbranch
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_grouppatientbranch");
            }

            set
            {
                this.OnPropertyChanging("cvt_grouppatientbranch");
                this.SetAttributeValue("cvt_grouppatientbranch", value);
                this.OnPropertyChanged("cvt_grouppatientbranch");
            }
        }

        /// <summary>
        /// Unique identifier for Facility associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_patientfacility")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_PatientFacility
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_patientfacility");
            }

            set
            {
                this.OnPropertyChanging("cvt_PatientFacility");
                this.SetAttributeValue("cvt_patientfacility", value);
                this.OnPropertyChanged("cvt_PatientFacility");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_patientsites")]
        public string cvt_patientsites
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_patientsites");
            }

            set
            {
                this.OnPropertyChanging("cvt_patientsites");
                this.SetAttributeValue("cvt_patientsites", value);
                this.OnPropertyChanged("cvt_patientsites");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_patientsitetctteam")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_patientsitetctteam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_patientsitetctteam");
            }

            set
            {
                this.OnPropertyChanging("cvt_patientsitetctteam");
                this.SetAttributeValue("cvt_patientsitetctteam", value);
                this.OnPropertyChanged("cvt_patientsitetctteam");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_patsiteusers")]
        public string cvt_patsiteusers
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_patsiteusers");
            }

            set
            {
                this.OnPropertyChanging("cvt_patsiteusers");
                this.SetAttributeValue("cvt_patsiteusers", value);
                this.OnPropertyChanged("cvt_patsiteusers");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_patsitevistaclinics")]
        public string cvt_patsitevistaclinics
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_patsitevistaclinics");
            }

            set
            {
                this.OnPropertyChanging("cvt_patsitevistaclinics");
                this.SetAttributeValue("cvt_patsitevistaclinics", value);
                this.OnPropertyChanged("cvt_patsitevistaclinics");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_patvistaclinic")]
        public string cvt_PatVistAClinic
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_patvistaclinic");
            }

            set
            {
                this.OnPropertyChanging("cvt_PatVistAClinic");
                this.SetAttributeValue("cvt_patvistaclinic", value);
                this.OnPropertyChanged("cvt_PatVistAClinic");
            }
        }

        /// <summary>
        /// Unique identifier for Facility associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_providerfacility")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_ProviderFacility
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_providerfacility");
            }

            set
            {
                this.OnPropertyChanging("cvt_ProviderFacility");
                this.SetAttributeValue("cvt_providerfacility", value);
                this.OnPropertyChanged("cvt_ProviderFacility");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_providerlocationtype")]
        public System.Nullable<bool> cvt_ProviderLocationType
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("cvt_providerlocationtype");
            }

            set
            {
                this.OnPropertyChanging("cvt_ProviderLocationType");
                this.SetAttributeValue("cvt_providerlocationtype", value);
                this.OnPropertyChanged("cvt_ProviderLocationType");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_providers")]
        public string cvt_providers
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_providers");
            }

            set
            {
                this.OnPropertyChanging("cvt_providers");
                this.SetAttributeValue("cvt_providers", value);
                this.OnPropertyChanged("cvt_providers");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_providersitetctteam")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_providersitetctteam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_providersitetctteam");
            }

            set
            {
                this.OnPropertyChanging("cvt_providersitetctteam");
                this.SetAttributeValue("cvt_providersitetctteam", value);
                this.OnPropertyChanged("cvt_providersitetctteam");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_provistaclinic")]
        public string cvt_ProVistAClinic
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_provistaclinic");
            }

            set
            {
                this.OnPropertyChanging("cvt_ProVistAClinic");
                this.SetAttributeValue("cvt_provistaclinic", value);
                this.OnPropertyChanged("cvt_ProVistAClinic");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_provsitevistaclinics")]
        public string cvt_provsitevistaclinics
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_provsitevistaclinics");
            }

            set
            {
                this.OnPropertyChanging("cvt_provsitevistaclinics");
                this.SetAttributeValue("cvt_provsitevistaclinics", value);
                this.OnPropertyChanged("cvt_provsitevistaclinics");
            }
        }

        /// <summary>
        /// Unique identifier for Master TSA associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedmasterid")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_RelatedMasterId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_relatedmasterid");
            }

            set
            {
                this.OnPropertyChanging("cvt_RelatedMasterId");
                this.SetAttributeValue("cvt_relatedmasterid", value);
                this.OnPropertyChanged("cvt_RelatedMasterId");
            }
        }

        /// <summary>
        /// Unique identifier for MCS Site associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedpatientsiteid")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_relatedpatientsiteid
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_relatedpatientsiteid");
            }

            set
            {
                this.OnPropertyChanging("cvt_relatedpatientsiteid");
                this.SetAttributeValue("cvt_relatedpatientsiteid", value);
                this.OnPropertyChanged("cvt_relatedpatientsiteid");
            }
        }

        /// <summary>
        /// Unique identifier for MCS Site associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedprovidersiteid")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_relatedprovidersiteid
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_relatedprovidersiteid");
            }

            set
            {
                this.OnPropertyChanging("cvt_relatedprovidersiteid");
                this.SetAttributeValue("cvt_relatedprovidersiteid", value);
                this.OnPropertyChanged("cvt_relatedprovidersiteid");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_schedulinginstructions")]
        public string cvt_SchedulingInstructions
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_schedulinginstructions");
            }

            set
            {
                this.OnPropertyChanging("cvt_SchedulingInstructions");
                this.SetAttributeValue("cvt_schedulinginstructions", value);
                this.OnPropertyChanged("cvt_SchedulingInstructions");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_servicelevels")]
        public System.Nullable<cvt_telehealthservicelevels> cvt_ServiceLevels
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("cvt_servicelevels");
                if ((optionSet != null))
                {
                    return ((cvt_telehealthservicelevels)(System.Enum.ToObject(typeof(cvt_telehealthservicelevels), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("cvt_ServiceLevels");
                if ((value == null))
                {
                    this.SetAttributeValue("cvt_servicelevels", null);
                }
                else
                {
                    this.SetAttributeValue("cvt_servicelevels", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("cvt_ServiceLevels");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_servicescope")]
        public System.Nullable<mcs_servicescvt_ServiceScope> cvt_ServiceScope
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("cvt_servicescope");
                if ((optionSet != null))
                {
                    return ((mcs_servicescvt_ServiceScope)(System.Enum.ToObject(typeof(mcs_servicescvt_ServiceScope), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("cvt_ServiceScope");
                if ((value == null))
                {
                    this.SetAttributeValue("cvt_servicescope", null);
                }
                else
                {
                    this.SetAttributeValue("cvt_servicescope", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("cvt_ServiceScope");
            }
        }

        /// <summary>
        /// Unique identifier for Specialty Sub Type associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_servicesubtype")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_servicesubtype
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_servicesubtype");
            }

            set
            {
                this.OnPropertyChanging("cvt_servicesubtype");
                this.SetAttributeValue("cvt_servicesubtype", value);
                this.OnPropertyChanged("cvt_servicesubtype");
            }
        }

        /// <summary>
        /// Unique identifier for Specialty associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_servicetype")]
        public Microsoft.Xrm.Sdk.EntityReference cvt_servicetype
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cvt_servicetype");
            }

            set
            {
                this.OnPropertyChanging("cvt_servicetype");
                this.SetAttributeValue("cvt_servicetype", value);
                this.OnPropertyChanged("cvt_servicetype");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_specialtyoperationssupplement")]
        public string cvt_specialtyoperationssupplement
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_specialtyoperationssupplement");
            }

            set
            {
                this.OnPropertyChanging("cvt_specialtyoperationssupplement");
                this.SetAttributeValue("cvt_specialtyoperationssupplement", value);
                this.OnPropertyChanged("cvt_specialtyoperationssupplement");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_startevery")]
        public System.Nullable<int> cvt_startevery
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("cvt_startevery");
            }

            set
            {
                this.OnPropertyChanging("cvt_startevery");
                this.SetAttributeValue("cvt_startevery", value);
                this.OnPropertyChanged("cvt_startevery");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_telehealthoperationsmanual")]
        public string cvt_telehealthoperationsmanual
        {
            get
            {
                return this.GetAttributeValue<string>("cvt_telehealthoperationsmanual");
            }

            set
            {
                this.OnPropertyChanging("cvt_telehealthoperationsmanual");
                this.SetAttributeValue("cvt_telehealthoperationsmanual", value);
                this.OnPropertyChanged("cvt_telehealthoperationsmanual");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_type")]
        public System.Nullable<bool> cvt_Type
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("cvt_type");
            }

            set
            {
                this.OnPropertyChanging("cvt_Type");
                this.SetAttributeValue("cvt_type", value);
                this.OnPropertyChanged("cvt_Type");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_updatepatproresources")]
        public System.Nullable<bool> cvt_updatepatproresources
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("cvt_updatepatproresources");
            }

            set
            {
                this.OnPropertyChanging("cvt_updatepatproresources");
                this.SetAttributeValue("cvt_updatepatproresources", value);
                this.OnPropertyChanged("cvt_updatepatproresources");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }

            set
            {
                this.OnPropertyChanging("ImportSequenceNumber");
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_capacity")]
        public System.Nullable<int> mcs_Capacity
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("mcs_capacity");
            }

            set
            {
                this.OnPropertyChanging("mcs_Capacity");
                this.SetAttributeValue("mcs_capacity", value);
                this.OnPropertyChanged("mcs_Capacity");
            }
        }

        /// <summary>
        /// The name of the custom entity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_name")]
        public string mcs_name
        {
            get
            {
                return this.GetAttributeValue<string>("mcs_name");
            }

            set
            {
                this.OnPropertyChanging("mcs_name");
                this.SetAttributeValue("mcs_name", value);
                this.OnPropertyChanged("mcs_name");
            }
        }

        /// <summary>
        /// Unique identifier for Service associated with TSA.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_relatedserviceid")]
        public Microsoft.Xrm.Sdk.EntityReference mcs_RelatedServiceId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mcs_relatedserviceid");
            }

            set
            {
                this.OnPropertyChanging("mcs_RelatedServiceId");
                this.SetAttributeValue("mcs_relatedserviceid", value);
                this.OnPropertyChanged("mcs_RelatedServiceId");
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_servicesid")]
        public System.Nullable<System.Guid> mcs_servicesId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("mcs_servicesid");
            }

            set
            {
                this.OnPropertyChanging("mcs_servicesId");
                this.SetAttributeValue("mcs_servicesid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }

                this.OnPropertyChanged("mcs_servicesId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_servicesid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }

            set
            {
                this.mcs_servicesId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_vistaclinicnumber")]
        public System.Nullable<int> mcs_vistaclinicnumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("mcs_vistaclinicnumber");
            }

            set
            {
                this.OnPropertyChanging("mcs_vistaclinicnumber");
                this.SetAttributeValue("mcs_vistaclinicnumber", value);
                this.OnPropertyChanged("mcs_vistaclinicnumber");
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }

            set
            {
                this.OnPropertyChanging("OverriddenCreatedOn");
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("OverriddenCreatedOn");
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference OwnerId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }

            set
            {
                this.OnPropertyChanging("OwnerId");
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("OwnerId");
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Status of the TSA
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public System.Nullable<mcs_services_statecode> statecode
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((mcs_services_statecode)(System.Enum.ToObject(typeof(mcs_services_statecode), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("statecode");
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("statecode");
            }
        }

        /// <summary>
        /// Reason for the status of the TSA
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public Microsoft.Xrm.Sdk.OptionSetValue statuscode
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
                if ((optionSet != null))
                {
                    return optionSet;
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("statuscode");
                if ((value == null))
                {
                    this.SetAttributeValue("statuscode", null);
                }
                else
                {
                    this.SetAttributeValue("statuscode", value);
                }

                this.OnPropertyChanged("statuscode");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }

            set
            {
                this.OnPropertyChanging("TimeZoneRuleVersionNumber");
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }

            set
            {
                this.OnPropertyChanging("UTCConversionTimeZoneCode");
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// 1:N cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid")]
        public System.Collections.Generic.IEnumerable<cvt_patientresourcegroup> cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid
        {
            get
            {
                return this.GetRelatedEntities<cvt_patientresourcegroup>("cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid");
                this.SetRelatedEntities<cvt_patientresourcegroup>("cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid", null, value);
                this.OnPropertyChanged("cvt_mcs_services_cvt_patientresourcegroup_RelatedTSAid");
            }
        }

        /// <summary>
        /// 1:N cvt_mcs_services_cvt_providerresourcegroup_RelatedTSAid
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_services_cvt_providerresourcegroup_RelatedTSAid")]
        public System.Collections.Generic.IEnumerable<cvt_providerresourcegroup> cvt_mcs_services_cvt_providerresourcegroup_RelatedTSAid
        {
            get
            {
                return this.GetRelatedEntities<cvt_providerresourcegroup>("cvt_mcs_services_cvt_providerresourcegroup_RelatedTSAid", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_services_cvt_providerresourcegroup_RelatedTSAid");
                this.SetRelatedEntities<cvt_providerresourcegroup>("cvt_mcs_services_cvt_providerresourcegroup_RelatedTSAid", null, value);
                this.OnPropertyChanged("cvt_mcs_services_cvt_providerresourcegroup_RelatedTSAid");
            }
        }

        /// <summary>
        /// 1:N mcs_mcs_services_serviceappointment_relatedtsa
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_mcs_services_serviceappointment_relatedtsa")]
        public System.Collections.Generic.IEnumerable<ServiceAppointment> mcs_mcs_services_serviceappointment_relatedtsa
        {
            get
            {
                return this.GetRelatedEntities<ServiceAppointment>("mcs_mcs_services_serviceappointment_relatedtsa", null);
            }

            set
            {
                this.OnPropertyChanging("mcs_mcs_services_serviceappointment_relatedtsa");
                this.SetRelatedEntities<ServiceAppointment>("mcs_mcs_services_serviceappointment_relatedtsa", null, value);
                this.OnPropertyChanged("mcs_mcs_services_serviceappointment_relatedtsa");
            }
        }

        /// <summary>
        /// 1:N mcs_services_ActivityPointers
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_ActivityPointers")]
        public System.Collections.Generic.IEnumerable<ActivityPointer> mcs_services_ActivityPointers
        {
            get
            {
                return this.GetRelatedEntities<ActivityPointer>("mcs_services_ActivityPointers", null);
            }

            set
            {
                this.OnPropertyChanging("mcs_services_ActivityPointers");
                this.SetRelatedEntities<ActivityPointer>("mcs_services_ActivityPointers", null, value);
                this.OnPropertyChanged("mcs_services_ActivityPointers");
            }
        }

        /// <summary>
        /// 1:N mcs_services_Annotations
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_Annotations")]
        public System.Collections.Generic.IEnumerable<Annotation> mcs_services_Annotations
        {
            get
            {
                return this.GetRelatedEntities<Annotation>("mcs_services_Annotations", null);
            }

            set
            {
                this.OnPropertyChanging("mcs_services_Annotations");
                this.SetRelatedEntities<Annotation>("mcs_services_Annotations", null, value);
                this.OnPropertyChanged("mcs_services_Annotations");
            }
        }

        /// <summary>
        /// 1:N mcs_services_Appointments
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_Appointments")]
        public System.Collections.Generic.IEnumerable<Appointment> mcs_services_Appointments
        {
            get
            {
                return this.GetRelatedEntities<Appointment>("mcs_services_Appointments", null);
            }

            set
            {
                this.OnPropertyChanging("mcs_services_Appointments");
                this.SetRelatedEntities<Appointment>("mcs_services_Appointments", null, value);
                this.OnPropertyChanged("mcs_services_Appointments");
            }
        }

        /// <summary>
        /// 1:N mcs_services_AsyncOperations
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_AsyncOperations")]
        public System.Collections.Generic.IEnumerable<SystemJob> SystemJobs_Regarding
        {
            get
            {
                return this.GetRelatedEntities<SystemJob>("mcs_services_AsyncOperations", null);
            }

            set
            {
                this.OnPropertyChanging("SystemJobs_Regarding");
                this.SetRelatedEntities<SystemJob>("mcs_services_AsyncOperations", null, value);
                this.OnPropertyChanged("SystemJobs_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_services_BulkDeleteFailures
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_BulkDeleteFailures")]
        public System.Collections.Generic.IEnumerable<BulkDeleteFailure> BulkDeleteFailures_Name
        {
            get
            {
                return this.GetRelatedEntities<BulkDeleteFailure>("mcs_services_BulkDeleteFailures", null);
            }

            set
            {
                this.OnPropertyChanging("BulkDeleteFailures_Name");
                this.SetRelatedEntities<BulkDeleteFailure>("mcs_services_BulkDeleteFailures", null, value);
                this.OnPropertyChanged("BulkDeleteFailures_Name");
            }
        }

        /// <summary>
        /// 1:N mcs_services_connections1
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_connections1")]
        public System.Collections.Generic.IEnumerable<Connection> Connections_ConnectedFrom
        {
            get
            {
                return this.GetRelatedEntities<Connection>("mcs_services_connections1", null);
            }

            set
            {
                this.OnPropertyChanging("Connections_ConnectedFrom");
                this.SetRelatedEntities<Connection>("mcs_services_connections1", null, value);
                this.OnPropertyChanged("Connections_ConnectedFrom");
            }
        }

        /// <summary>
        /// 1:N mcs_services_connections2
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_connections2")]
        public System.Collections.Generic.IEnumerable<Connection> Connections_ConnectedTo
        {
            get
            {
                return this.GetRelatedEntities<Connection>("mcs_services_connections2", null);
            }

            set
            {
                this.OnPropertyChanging("Connections_ConnectedTo");
                this.SetRelatedEntities<Connection>("mcs_services_connections2", null, value);
                this.OnPropertyChanged("Connections_ConnectedTo");
            }
        }

        /// <summary>
        /// 1:N mcs_services_Emails
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_Emails")]
        public System.Collections.Generic.IEnumerable<Email> mcs_services_Emails
        {
            get
            {
                return this.GetRelatedEntities<Email>("mcs_services_Emails", null);
            }

            set
            {
                this.OnPropertyChanging("mcs_services_Emails");
                this.SetRelatedEntities<Email>("mcs_services_Emails", null, value);
                this.OnPropertyChanged("mcs_services_Emails");
            }
        }

        /// <summary>
        /// 1:N mcs_services_MailboxTrackingFolders
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_MailboxTrackingFolders")]
        public System.Collections.Generic.IEnumerable<MailboxAutoTrackingFolder> MailboxAutoTrackingFolders_RegardingObjectId
        {
            get
            {
                return this.GetRelatedEntities<MailboxAutoTrackingFolder>("mcs_services_MailboxTrackingFolders", null);
            }

            set
            {
                this.OnPropertyChanging("MailboxAutoTrackingFolders_RegardingObjectId");
                this.SetRelatedEntities<MailboxAutoTrackingFolder>("mcs_services_MailboxTrackingFolders", null, value);
                this.OnPropertyChanged("MailboxAutoTrackingFolders_RegardingObjectId");
            }
        }

        /// <summary>
        /// 1:N mcs_services_PrincipalObjectAttributeAccesses
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_PrincipalObjectAttributeAccesses")]
        public System.Collections.Generic.IEnumerable<FieldSharing> FieldSharing_EntityInstance
        {
            get
            {
                return this.GetRelatedEntities<FieldSharing>("mcs_services_PrincipalObjectAttributeAccesses", null);
            }

            set
            {
                this.OnPropertyChanging("FieldSharing_EntityInstance");
                this.SetRelatedEntities<FieldSharing>("mcs_services_PrincipalObjectAttributeAccesses", null, value);
                this.OnPropertyChanged("FieldSharing_EntityInstance");
            }
        }

        /// <summary>
        /// 1:N mcs_services_ProcessSession
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_ProcessSession")]
        public System.Collections.Generic.IEnumerable<ProcessSession> ProcessSessions_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ProcessSession>("mcs_services_ProcessSession", null);
            }

            set
            {
                this.OnPropertyChanging("ProcessSessions_Regarding");
                this.SetRelatedEntities<ProcessSession>("mcs_services_ProcessSession", null, value);
                this.OnPropertyChanged("ProcessSessions_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_services_QueueItems
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_QueueItems")]
        public System.Collections.Generic.IEnumerable<QueueItem> QueueItems_Object
        {
            get
            {
                return this.GetRelatedEntities<QueueItem>("mcs_services_QueueItems", null);
            }

            set
            {
                this.OnPropertyChanging("QueueItems_Object");
                this.SetRelatedEntities<QueueItem>("mcs_services_QueueItems", null, value);
                this.OnPropertyChanged("QueueItems_Object");
            }
        }

        /// <summary>
        /// 1:N mcs_services_RecurringAppointmentMasters
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_RecurringAppointmentMasters")]
        public System.Collections.Generic.IEnumerable<RecurringAppointmentMaster> mcs_services_RecurringAppointmentMasters
        {
            get
            {
                return this.GetRelatedEntities<RecurringAppointmentMaster>("mcs_services_RecurringAppointmentMasters", null);
            }

            set
            {
                this.OnPropertyChanging("mcs_services_RecurringAppointmentMasters");
                this.SetRelatedEntities<RecurringAppointmentMaster>("mcs_services_RecurringAppointmentMasters", null, value);
                this.OnPropertyChanged("mcs_services_RecurringAppointmentMasters");
            }
        }

        /// <summary>
        /// 1:N mcs_services_ServiceAppointments
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_ServiceAppointments")]
        public System.Collections.Generic.IEnumerable<ServiceAppointment> mcs_services_ServiceAppointments
        {
            get
            {
                return this.GetRelatedEntities<ServiceAppointment>("mcs_services_ServiceAppointments", null);
            }

            set
            {
                this.OnPropertyChanging("mcs_services_ServiceAppointments");
                this.SetRelatedEntities<ServiceAppointment>("mcs_services_ServiceAppointments", null, value);
                this.OnPropertyChanged("mcs_services_ServiceAppointments");
            }
        }

        /// <summary>
        /// 1:N mcs_services_SyncErrors
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_SyncErrors")]
        public System.Collections.Generic.IEnumerable<SyncError> SyncErrors_Record
        {
            get
            {
                return this.GetRelatedEntities<SyncError>("mcs_services_SyncErrors", null);
            }

            set
            {
                this.OnPropertyChanging("SyncErrors_Record");
                this.SetRelatedEntities<SyncError>("mcs_services_SyncErrors", null, value);
                this.OnPropertyChanged("SyncErrors_Record");
            }
        }

        /// <summary>
        /// 1:N mcs_services_Tasks
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_Tasks")]
        public System.Collections.Generic.IEnumerable<Task> Tasks_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Task>("mcs_services_Tasks", null);
            }

            set
            {
                this.OnPropertyChanging("Tasks_Regarding");
                this.SetRelatedEntities<Task>("mcs_services_Tasks", null, value);
                this.OnPropertyChanged("Tasks_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_services_UserEntityInstanceDatas
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_services_UserEntityInstanceDatas")]
        public System.Collections.Generic.IEnumerable<UserEntityInstanceData> UserEntityInstanceData_ObjectId
        {
            get
            {
                return this.GetRelatedEntities<UserEntityInstanceData>("mcs_services_UserEntityInstanceDatas", null);
            }

            set
            {
                this.OnPropertyChanging("UserEntityInstanceData_ObjectId");
                this.SetRelatedEntities<UserEntityInstanceData>("mcs_services_UserEntityInstanceDatas", null, value);
                this.OnPropertyChanged("UserEntityInstanceData_ObjectId");
            }
        }

        /// <summary>
        /// N:1 business_unit_mcs_services
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_mcs_services")]
        public BusinessUnit business_unit_mcs_services
        {
            get
            {
                return this.GetRelatedEntity<BusinessUnit>("business_unit_mcs_services", null);
            }
        }

        /// <summary>
        /// N:1 cvt_cvt_mastertsa_mcs_services
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedmasterid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_cvt_mastertsa_mcs_services")]
        public cvt_mastertsa cvt_cvt_mastertsa_mcs_services
        {
            get
            {
                return this.GetRelatedEntity<cvt_mastertsa>("cvt_cvt_mastertsa_mcs_services", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_cvt_mastertsa_mcs_services");
                this.SetRelatedEntity<cvt_mastertsa>("cvt_cvt_mastertsa_mcs_services", null, value);
                this.OnPropertyChanged("cvt_cvt_mastertsa_mcs_services");
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_facility_mcs_services_PatientFacility
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_patientfacility")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_facility_mcs_services_PatientFacility")]
        public mcs_facility cvt_mcs_facility_mcs_services_PatientFacility
        {
            get
            {
                return this.GetRelatedEntity<mcs_facility>("cvt_mcs_facility_mcs_services_PatientFacility", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_facility_mcs_services_PatientFacility");
                this.SetRelatedEntity<mcs_facility>("cvt_mcs_facility_mcs_services_PatientFacility", null, value);
                this.OnPropertyChanged("cvt_mcs_facility_mcs_services_PatientFacility");
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_facility_mcs_services_ProviderFacility
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_providerfacility")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_facility_mcs_services_ProviderFacility")]
        public mcs_facility cvt_mcs_facility_mcs_services_ProviderFacility
        {
            get
            {
                return this.GetRelatedEntity<mcs_facility>("cvt_mcs_facility_mcs_services_ProviderFacility", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_facility_mcs_services_ProviderFacility");
                this.SetRelatedEntity<mcs_facility>("cvt_mcs_facility_mcs_services_ProviderFacility", null, value);
                this.OnPropertyChanged("cvt_mcs_facility_mcs_services_ProviderFacility");
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_resource_mcs_services_BulkAddResource
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_bulkaddresource")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_resource_mcs_services_BulkAddResource")]
        public mcs_resource cvt_mcs_resource_mcs_services_BulkAddResource
        {
            get
            {
                return this.GetRelatedEntity<mcs_resource>("cvt_mcs_resource_mcs_services_BulkAddResource", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_resource_mcs_services_BulkAddResource");
                this.SetRelatedEntity<mcs_resource>("cvt_mcs_resource_mcs_services_BulkAddResource", null, value);
                this.OnPropertyChanged("cvt_mcs_resource_mcs_services_BulkAddResource");
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_resource_mcs_services_BulkRemoveResource
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_bulkremoveresource")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_resource_mcs_services_BulkRemoveResource")]
        public mcs_resource cvt_mcs_resource_mcs_services_BulkRemoveResource
        {
            get
            {
                return this.GetRelatedEntity<mcs_resource>("cvt_mcs_resource_mcs_services_BulkRemoveResource", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_resource_mcs_services_BulkRemoveResource");
                this.SetRelatedEntity<mcs_resource>("cvt_mcs_resource_mcs_services_BulkRemoveResource", null, value);
                this.OnPropertyChanged("cvt_mcs_resource_mcs_services_BulkRemoveResource");
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_resourcegroup_mcs_services_BulkAddResourceGroup
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_bulkaddresourcegroup")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_resourcegroup_mcs_services_BulkAddResourceGroup")]
        public mcs_resourcegroup cvt_mcs_resourcegroup_mcs_services_BulkAddResourceGroup
        {
            get
            {
                return this.GetRelatedEntity<mcs_resourcegroup>("cvt_mcs_resourcegroup_mcs_services_BulkAddResourceGroup", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_resourcegroup_mcs_services_BulkAddResourceGroup");
                this.SetRelatedEntity<mcs_resourcegroup>("cvt_mcs_resourcegroup_mcs_services_BulkAddResourceGroup", null, value);
                this.OnPropertyChanged("cvt_mcs_resourcegroup_mcs_services_BulkAddResourceGroup");
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_resourcegroup_mcs_services_BulkRemoveResourceGroup
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_bulkremoveresourcegroup")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_resourcegroup_mcs_services_BulkRemoveResourceGroup")]
        public mcs_resourcegroup cvt_mcs_resourcegroup_mcs_services_BulkRemoveResourceGroup
        {
            get
            {
                return this.GetRelatedEntity<mcs_resourcegroup>("cvt_mcs_resourcegroup_mcs_services_BulkRemoveResourceGroup", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_resourcegroup_mcs_services_BulkRemoveResourceGroup");
                this.SetRelatedEntity<mcs_resourcegroup>("cvt_mcs_resourcegroup_mcs_services_BulkRemoveResourceGroup", null, value);
                this.OnPropertyChanged("cvt_mcs_resourcegroup_mcs_services_BulkRemoveResourceGroup");
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_servicesubtype_mcs_services_servicesubtype
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_servicesubtype")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_servicesubtype_mcs_services_servicesubtype")]
        public mcs_servicesubtype cvt_mcs_servicesubtype_mcs_services_servicesubtype
        {
            get
            {
                return this.GetRelatedEntity<mcs_servicesubtype>("cvt_mcs_servicesubtype_mcs_services_servicesubtype", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_servicesubtype_mcs_services_servicesubtype");
                this.SetRelatedEntity<mcs_servicesubtype>("cvt_mcs_servicesubtype_mcs_services_servicesubtype", null, value);
                this.OnPropertyChanged("cvt_mcs_servicesubtype_mcs_services_servicesubtype");
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_servicetype_mcs_services_servicetype
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_servicetype")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_servicetype_mcs_services_servicetype")]
        public mcs_servicetype cvt_mcs_servicetype_mcs_services_servicetype
        {
            get
            {
                return this.GetRelatedEntity<mcs_servicetype>("cvt_mcs_servicetype_mcs_services_servicetype", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_servicetype_mcs_services_servicetype");
                this.SetRelatedEntity<mcs_servicetype>("cvt_mcs_servicetype_mcs_services_servicetype", null, value);
                this.OnPropertyChanged("cvt_mcs_servicetype_mcs_services_servicetype");
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_site_mcs_services_relatedpatientsite
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedpatientsiteid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_site_mcs_services_relatedpatientsite")]
        public mcs_site cvt_mcs_site_mcs_services_relatedpatientsite
        {
            get
            {
                return this.GetRelatedEntity<mcs_site>("cvt_mcs_site_mcs_services_relatedpatientsite", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_site_mcs_services_relatedpatientsite");
                this.SetRelatedEntity<mcs_site>("cvt_mcs_site_mcs_services_relatedpatientsite", null, value);
                this.OnPropertyChanged("cvt_mcs_site_mcs_services_relatedpatientsite");
            }
        }

        /// <summary>
        /// N:1 cvt_mcs_site_mcs_services_relatedprovidersiteid
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_relatedprovidersiteid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_mcs_site_mcs_services_relatedprovidersiteid")]
        public mcs_site cvt_mcs_site_mcs_services_relatedprovidersiteid
        {
            get
            {
                return this.GetRelatedEntity<mcs_site>("cvt_mcs_site_mcs_services_relatedprovidersiteid", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_mcs_site_mcs_services_relatedprovidersiteid");
                this.SetRelatedEntity<mcs_site>("cvt_mcs_site_mcs_services_relatedprovidersiteid", null, value);
                this.OnPropertyChanged("cvt_mcs_site_mcs_services_relatedprovidersiteid");
            }
        }

        /// <summary>
        /// N:1 cvt_systemuser_mcs_services_BulkAddUser
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_bulkadduser")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_systemuser_mcs_services_BulkAddUser")]
        public SystemUser cvt_systemuser_mcs_services_BulkAddUser
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("cvt_systemuser_mcs_services_BulkAddUser", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_systemuser_mcs_services_BulkAddUser");
                this.SetRelatedEntity<SystemUser>("cvt_systemuser_mcs_services_BulkAddUser", null, value);
                this.OnPropertyChanged("cvt_systemuser_mcs_services_BulkAddUser");
            }
        }

        /// <summary>
        /// N:1 cvt_systemuser_mcs_services_BulkRemoveUser
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_bulkremoveuser")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_systemuser_mcs_services_BulkRemoveUser")]
        public SystemUser cvt_systemuser_mcs_services_BulkRemoveUser
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("cvt_systemuser_mcs_services_BulkRemoveUser", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_systemuser_mcs_services_BulkRemoveUser");
                this.SetRelatedEntity<SystemUser>("cvt_systemuser_mcs_services_BulkRemoveUser", null, value);
                this.OnPropertyChanged("cvt_systemuser_mcs_services_BulkRemoveUser");
            }
        }

        /// <summary>
        /// N:1 cvt_team_mcs_services_patientsitetctteam
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_patientsitetctteam")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_team_mcs_services_patientsitetctteam")]
        public Team cvt_team_mcs_services_patientsitetctteam
        {
            get
            {
                return this.GetRelatedEntity<Team>("cvt_team_mcs_services_patientsitetctteam", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_team_mcs_services_patientsitetctteam");
                this.SetRelatedEntity<Team>("cvt_team_mcs_services_patientsitetctteam", null, value);
                this.OnPropertyChanged("cvt_team_mcs_services_patientsitetctteam");
            }
        }

        /// <summary>
        /// N:1 cvt_team_mcs_services_providersitetctteam
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cvt_providersitetctteam")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cvt_team_mcs_services_providersitetctteam")]
        public Team cvt_team_mcs_services_providersitetctteam
        {
            get
            {
                return this.GetRelatedEntity<Team>("cvt_team_mcs_services_providersitetctteam", null);
            }

            set
            {
                this.OnPropertyChanging("cvt_team_mcs_services_providersitetctteam");
                this.SetRelatedEntity<Team>("cvt_team_mcs_services_providersitetctteam", null, value);
                this.OnPropertyChanged("cvt_team_mcs_services_providersitetctteam");
            }
        }

        /// <summary>
        /// N:1 lk_mcs_services_createdby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_mcs_services_createdby")]
        public SystemUser lk_mcs_services_createdby
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_mcs_services_createdby", null);
            }
        }

        /// <summary>
        /// N:1 lk_mcs_services_createdonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_mcs_services_createdonbehalfby")]
        public SystemUser lk_mcs_services_createdonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_mcs_services_createdonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 lk_mcs_services_modifiedby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_mcs_services_modifiedby")]
        public SystemUser lk_mcs_services_modifiedby
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_mcs_services_modifiedby", null);
            }
        }

        /// <summary>
        /// N:1 lk_mcs_services_modifiedonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_mcs_services_modifiedonbehalfby")]
        public SystemUser lk_mcs_services_modifiedonbehalfby
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_mcs_services_modifiedonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 mcs_service_mcs_services_RelatedServiceId
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_relatedserviceid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_service_mcs_services_RelatedServiceId")]
        public Service mcs_service_mcs_services_RelatedServiceId
        {
            get
            {
                return this.GetRelatedEntity<Service>("mcs_service_mcs_services_RelatedServiceId", null);
            }

            set
            {
                this.OnPropertyChanging("mcs_service_mcs_services_RelatedServiceId");
                this.SetRelatedEntity<Service>("mcs_service_mcs_services_RelatedServiceId", null, value);
                this.OnPropertyChanged("mcs_service_mcs_services_RelatedServiceId");
            }
        }

        /// <summary>
        /// N:1 team_mcs_services
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_mcs_services")]
        public Team team_mcs_services
        {
            get
            {
                return this.GetRelatedEntity<Team>("team_mcs_services", null);
            }
        }

        /// <summary>
        /// N:1 user_mcs_services
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_mcs_services")]
        public SystemUser user_mcs_services
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("user_mcs_services", null);
            }
        }
    }
}