//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using VA.TMP.DataModel.OptionSets;

namespace VA.TMP.DataModel
{
    /// <summary>
    /// 
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("mcs_message")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public partial class Message : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public Message(): base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "mcs_message";
        public const string EntityLogicalCollectionName = "mcs_messages";
        public const string EntitySetName = "mcs_messages";
        public const int EntityTypeCode = 10024;
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        private void OnPropertyChanging(string propertyName)
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Unique identifier of the user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Date and time when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who created the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy_Delegate
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// Sequence number of the import that created this record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }

            set
            {
                this.OnPropertyChanging("ImportSequenceNumber");
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_createddatetime")]
        public string CreatedDatetime
        {
            get
            {
                return this.GetAttributeValue<string>("mcs_createddatetime");
            }

            set
            {
                this.OnPropertyChanging("CreatedDatetime");
                this.SetAttributeValue("mcs_createddatetime", value);
                this.OnPropertyChanged("CreatedDatetime");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_currentstate")]
        public System.Nullable<MessageState> CurrentState
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mcs_currentstate");
                if ((optionSet != null))
                {
                    return ((MessageState)(System.Enum.ToObject(typeof(MessageState), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("CurrentState");
                if ((value == null))
                {
                    this.SetAttributeValue("mcs_currentstate", null);
                }
                else
                {
                    this.SetAttributeValue("mcs_currentstate", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("CurrentState");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_currentstatus")]
        public System.Nullable<MessageStatus> CurrentStatus
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mcs_currentstatus");
                if ((optionSet != null))
                {
                    return ((MessageStatus)(System.Enum.ToObject(typeof(MessageStatus), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("CurrentStatus");
                if ((value == null))
                {
                    this.SetAttributeValue("mcs_currentstatus", null);
                }
                else
                {
                    this.SetAttributeValue("mcs_currentstatus", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("CurrentStatus");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_exception")]
        public string Exception
        {
            get
            {
                return this.GetAttributeValue<string>("mcs_exception");
            }

            set
            {
                this.OnPropertyChanging("Exception");
                this.SetAttributeValue("mcs_exception", value);
                this.OnPropertyChanged("Exception");
            }
        }

        /// <summary>
        /// Unique identifier for Interfaces associated with Message.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_exceptioninterface")]
        public Microsoft.Xrm.Sdk.EntityReference ExceptionInterface
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mcs_exceptioninterface");
            }

            set
            {
                this.OnPropertyChanging("ExceptionInterface");
                this.SetAttributeValue("mcs_exceptioninterface", value);
                this.OnPropertyChanged("ExceptionInterface");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_exceptionstep")]
        public string ExceptionStep
        {
            get
            {
                return this.GetAttributeValue<string>("mcs_exceptionstep");
            }

            set
            {
                this.OnPropertyChanging("ExceptionStep");
                this.SetAttributeValue("mcs_exceptionstep", value);
                this.OnPropertyChanged("ExceptionStep");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_finalizeddatetime")]
        public string FinalizedDatetime
        {
            get
            {
                return this.GetAttributeValue<string>("mcs_finalizeddatetime");
            }

            set
            {
                this.OnPropertyChanging("FinalizedDatetime");
                this.SetAttributeValue("mcs_finalizeddatetime", value);
                this.OnPropertyChanged("FinalizedDatetime");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_finalstate")]
        public System.Nullable<MessageState> FinalState
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mcs_finalstate");
                if ((optionSet != null))
                {
                    return ((MessageState)(System.Enum.ToObject(typeof(MessageState), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("FinalState");
                if ((value == null))
                {
                    this.SetAttributeValue("mcs_finalstate", null);
                }
                else
                {
                    this.SetAttributeValue("mcs_finalstate", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("FinalState");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_finalstatus")]
        public System.Nullable<MessageStatus> FinalStatus
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mcs_finalstatus");
                if ((optionSet != null))
                {
                    return ((MessageStatus)(System.Enum.ToObject(typeof(MessageStatus), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("FinalStatus");
                if ((value == null))
                {
                    this.SetAttributeValue("mcs_finalstatus", null);
                }
                else
                {
                    this.SetAttributeValue("mcs_finalstatus", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("FinalStatus");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_generatingentityid")]
        public string GeneratingEntityID
        {
            get
            {
                return this.GetAttributeValue<string>("mcs_generatingentityid");
            }

            set
            {
                this.OnPropertyChanging("GeneratingEntityID");
                this.SetAttributeValue("mcs_generatingentityid", value);
                this.OnPropertyChanged("GeneratingEntityID");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_generatingrecordid")]
        public string GeneratingRecordID
        {
            get
            {
                return this.GetAttributeValue<string>("mcs_generatingrecordid");
            }

            set
            {
                this.OnPropertyChanging("GeneratingRecordID");
                this.SetAttributeValue("mcs_generatingrecordid", value);
                this.OnPropertyChanged("GeneratingRecordID");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_lagtime")]
        public System.Nullable<int> LagTime_ms
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("mcs_lagtime");
            }

            set
            {
                this.OnPropertyChanging("LagTime_ms");
                this.SetAttributeValue("mcs_lagtime", value);
                this.OnPropertyChanged("LagTime_ms");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_messageaction")]
        public System.Nullable<Message_MessageAction> MessageAction
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mcs_messageaction");
                if ((optionSet != null))
                {
                    return ((Message_MessageAction)(System.Enum.ToObject(typeof(Message_MessageAction), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("MessageAction");
                if ((value == null))
                {
                    this.SetAttributeValue("mcs_messageaction", null);
                }
                else
                {
                    this.SetAttributeValue("mcs_messageaction", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("MessageAction");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_messagedirection")]
        public System.Nullable<MessageDirection> MessageDirection
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("mcs_messagedirection");
                if ((optionSet != null))
                {
                    return ((MessageDirection)(System.Enum.ToObject(typeof(MessageDirection), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("MessageDirection");
                if ((value == null))
                {
                    this.SetAttributeValue("mcs_messagedirection", null);
                }
                else
                {
                    this.SetAttributeValue("mcs_messagedirection", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("MessageDirection");
            }
        }

        /// <summary>
        /// Unique identifier for entity instances
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_messageid")]
        public System.Nullable<System.Guid> MessageId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("mcs_messageid");
            }

            set
            {
                this.OnPropertyChanging("MessageId");
                this.SetAttributeValue("mcs_messageid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }

                this.OnPropertyChanged("MessageId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_messageid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }

            set
            {
                this.MessageId = value;
            }
        }

        /// <summary>
        /// Unique identifier for Interface Message Type associated with Message.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_messagetype")]
        public Microsoft.Xrm.Sdk.EntityReference MessageType
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mcs_messagetype");
            }

            set
            {
                this.OnPropertyChanging("MessageType");
                this.SetAttributeValue("mcs_messagetype", value);
                this.OnPropertyChanged("MessageType");
            }
        }

        /// <summary>
        /// The name of the custom entity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_name")]
        public string Name
        {
            get
            {
                return this.GetAttributeValue<string>("mcs_name");
            }

            set
            {
                this.OnPropertyChanging("Name");
                this.SetAttributeValue("mcs_name", value);
                this.OnPropertyChanged("Name");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_processingtime")]
        public System.Nullable<int> ProcessingTime_ms
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("mcs_processingtime");
            }

            set
            {
                this.OnPropertyChanging("ProcessingTime_ms");
                this.SetAttributeValue("mcs_processingtime", value);
                this.OnPropertyChanged("ProcessingTime_ms");
            }
        }

        /// <summary>
        /// Unique identifier for Message associated with Message.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_relatedmessageid")]
        public Microsoft.Xrm.Sdk.EntityReference RelatedMessageID
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mcs_relatedmessageid");
            }

            set
            {
                this.OnPropertyChanging("RelatedMessageID");
                this.SetAttributeValue("mcs_relatedmessageid", value);
                this.OnPropertyChanged("RelatedMessageID");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_sentdatetime")]
        public string SentDatetime
        {
            get
            {
                return this.GetAttributeValue<string>("mcs_sentdatetime");
            }

            set
            {
                this.OnPropertyChanging("SentDatetime");
                this.SetAttributeValue("mcs_sentdatetime", value);
                this.OnPropertyChanged("SentDatetime");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_serializedmessage")]
        public string SerializedMessage
        {
            get
            {
                return this.GetAttributeValue<string>("mcs_serializedmessage");
            }

            set
            {
                this.OnPropertyChanging("SerializedMessage");
                this.SetAttributeValue("mcs_serializedmessage", value);
                this.OnPropertyChanged("SerializedMessage");
            }
        }

        /// <summary>
        /// Unique identifier of the user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Date and time when the record was modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Unique identifier of the delegate user who modified the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy_Delegate
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> RecordCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }

            set
            {
                this.OnPropertyChanging("RecordCreatedOn");
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("RecordCreatedOn");
            }
        }

        /// <summary>
        /// Owner Id
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference Owner
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }

            set
            {
                this.OnPropertyChanging("Owner");
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("Owner");
            }
        }

        /// <summary>
        /// Unique identifier for the business unit that owns the record
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// Unique identifier for the team that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// Unique identifier for the user that owns the record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Status of the Message
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public System.Nullable<Message_Status> Status
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((Message_Status)(System.Enum.ToObject(typeof(Message_Status), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("Status");
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Reason for the status of the Message
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public System.Nullable<Message_StatusReason> StatusReason
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
                if ((optionSet != null))
                {
                    return ((Message_StatusReason)(System.Enum.ToObject(typeof(Message_StatusReason), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("StatusReason");
                if ((value == null))
                {
                    this.SetAttributeValue("statuscode", null);
                }
                else
                {
                    this.SetAttributeValue("statuscode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("StatusReason");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }

            set
            {
                this.OnPropertyChanging("TimeZoneRuleVersionNumber");
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }

            set
            {
                this.OnPropertyChanging("UTCConversionTimeZoneCode");
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// 1:N mcs_mcs_message_mcs_message
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_mcs_message_mcs_message", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
        public System.Collections.Generic.IEnumerable<Message> Messages_RelatedMessageID_Referenced
        {
            get
            {
                return this.GetRelatedEntities<Message>("mcs_mcs_message_mcs_message", Microsoft.Xrm.Sdk.EntityRole.Referenced);
            }

            set
            {
                this.OnPropertyChanging("Messages_RelatedMessageID_Referenced");
                this.SetRelatedEntities<Message>("mcs_mcs_message_mcs_message", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
                this.OnPropertyChanged("Messages_RelatedMessageID_Referenced");
            }
        }

        /// <summary>
        /// 1:N mcs_mcs_message_mcs_messageaudit
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_mcs_message_mcs_messageaudit")]
        public System.Collections.Generic.IEnumerable<InterfaceAuditLog> InterfaceAuditLog_MessageID
        {
            get
            {
                return this.GetRelatedEntities<InterfaceAuditLog>("mcs_mcs_message_mcs_messageaudit", null);
            }

            set
            {
                this.OnPropertyChanging("InterfaceAuditLog_MessageID");
                this.SetRelatedEntities<InterfaceAuditLog>("mcs_mcs_message_mcs_messageaudit", null, value);
                this.OnPropertyChanged("InterfaceAuditLog_MessageID");
            }
        }

        /// <summary>
        /// 1:N mcs_message_ActivityPointers
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_ActivityPointers")]
        public System.Collections.Generic.IEnumerable<ActivityPointer> Activities_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ActivityPointer>("mcs_message_ActivityPointers", null);
            }

            set
            {
                this.OnPropertyChanging("Activities_Regarding");
                this.SetRelatedEntities<ActivityPointer>("mcs_message_ActivityPointers", null, value);
                this.OnPropertyChanged("Activities_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_message_Annotations
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_Annotations")]
        public System.Collections.Generic.IEnumerable<Annotation> Notes_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Annotation>("mcs_message_Annotations", null);
            }

            set
            {
                this.OnPropertyChanging("Notes_Regarding");
                this.SetRelatedEntities<Annotation>("mcs_message_Annotations", null, value);
                this.OnPropertyChanged("Notes_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_message_Appointments
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_Appointments")]
        public System.Collections.Generic.IEnumerable<Appointment> ReserveResources_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Appointment>("mcs_message_Appointments", null);
            }

            set
            {
                this.OnPropertyChanging("ReserveResources_Regarding");
                this.SetRelatedEntities<Appointment>("mcs_message_Appointments", null, value);
                this.OnPropertyChanged("ReserveResources_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_message_AsyncOperations
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_AsyncOperations")]
        public System.Collections.Generic.IEnumerable<SystemJob> SystemJobs_Regarding
        {
            get
            {
                return this.GetRelatedEntities<SystemJob>("mcs_message_AsyncOperations", null);
            }

            set
            {
                this.OnPropertyChanging("SystemJobs_Regarding");
                this.SetRelatedEntities<SystemJob>("mcs_message_AsyncOperations", null, value);
                this.OnPropertyChanged("SystemJobs_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_message_BulkDeleteFailures
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_BulkDeleteFailures")]
        public System.Collections.Generic.IEnumerable<BulkDeleteFailure> BulkDeleteFailures_Name
        {
            get
            {
                return this.GetRelatedEntities<BulkDeleteFailure>("mcs_message_BulkDeleteFailures", null);
            }

            set
            {
                this.OnPropertyChanging("BulkDeleteFailures_Name");
                this.SetRelatedEntities<BulkDeleteFailure>("mcs_message_BulkDeleteFailures", null, value);
                this.OnPropertyChanged("BulkDeleteFailures_Name");
            }
        }

        /// <summary>
        /// 1:N mcs_message_connections1
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_connections1")]
        public System.Collections.Generic.IEnumerable<Connection> Connections_ConnectedFrom
        {
            get
            {
                return this.GetRelatedEntities<Connection>("mcs_message_connections1", null);
            }

            set
            {
                this.OnPropertyChanging("Connections_ConnectedFrom");
                this.SetRelatedEntities<Connection>("mcs_message_connections1", null, value);
                this.OnPropertyChanged("Connections_ConnectedFrom");
            }
        }

        /// <summary>
        /// 1:N mcs_message_connections2
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_connections2")]
        public System.Collections.Generic.IEnumerable<Connection> Connections_ConnectedTo
        {
            get
            {
                return this.GetRelatedEntities<Connection>("mcs_message_connections2", null);
            }

            set
            {
                this.OnPropertyChanging("Connections_ConnectedTo");
                this.SetRelatedEntities<Connection>("mcs_message_connections2", null, value);
                this.OnPropertyChanged("Connections_ConnectedTo");
            }
        }

        /// <summary>
        /// 1:N mcs_message_Emails
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_Emails")]
        public System.Collections.Generic.IEnumerable<Email> EmailMessages_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Email>("mcs_message_Emails", null);
            }

            set
            {
                this.OnPropertyChanging("EmailMessages_Regarding");
                this.SetRelatedEntities<Email>("mcs_message_Emails", null, value);
                this.OnPropertyChanged("EmailMessages_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_message_MailboxTrackingFolders
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_MailboxTrackingFolders")]
        public System.Collections.Generic.IEnumerable<MailboxAutoTrackingFolder> MailboxAutoTrackingFolders_RegardingObjectId
        {
            get
            {
                return this.GetRelatedEntities<MailboxAutoTrackingFolder>("mcs_message_MailboxTrackingFolders", null);
            }

            set
            {
                this.OnPropertyChanging("MailboxAutoTrackingFolders_RegardingObjectId");
                this.SetRelatedEntities<MailboxAutoTrackingFolder>("mcs_message_MailboxTrackingFolders", null, value);
                this.OnPropertyChanged("MailboxAutoTrackingFolders_RegardingObjectId");
            }
        }

        /// <summary>
        /// 1:N mcs_message_PrincipalObjectAttributeAccesses
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_PrincipalObjectAttributeAccesses")]
        public System.Collections.Generic.IEnumerable<FieldSharing> FieldSharing_EntityInstance
        {
            get
            {
                return this.GetRelatedEntities<FieldSharing>("mcs_message_PrincipalObjectAttributeAccesses", null);
            }

            set
            {
                this.OnPropertyChanging("FieldSharing_EntityInstance");
                this.SetRelatedEntities<FieldSharing>("mcs_message_PrincipalObjectAttributeAccesses", null, value);
                this.OnPropertyChanged("FieldSharing_EntityInstance");
            }
        }

        /// <summary>
        /// 1:N mcs_message_ProcessSession
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_ProcessSession")]
        public System.Collections.Generic.IEnumerable<ProcessSession> ProcessSessions_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ProcessSession>("mcs_message_ProcessSession", null);
            }

            set
            {
                this.OnPropertyChanging("ProcessSessions_Regarding");
                this.SetRelatedEntities<ProcessSession>("mcs_message_ProcessSession", null, value);
                this.OnPropertyChanged("ProcessSessions_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_message_RecurringAppointmentMasters
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_RecurringAppointmentMasters")]
        public System.Collections.Generic.IEnumerable<RecurringAppointmentMaster> RecurringReserveResources_Regarding
        {
            get
            {
                return this.GetRelatedEntities<RecurringAppointmentMaster>("mcs_message_RecurringAppointmentMasters", null);
            }

            set
            {
                this.OnPropertyChanging("RecurringReserveResources_Regarding");
                this.SetRelatedEntities<RecurringAppointmentMaster>("mcs_message_RecurringAppointmentMasters", null, value);
                this.OnPropertyChanged("RecurringReserveResources_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_message_ServiceAppointments
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_ServiceAppointments")]
        public System.Collections.Generic.IEnumerable<ServiceAppointment> Appointments_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ServiceAppointment>("mcs_message_ServiceAppointments", null);
            }

            set
            {
                this.OnPropertyChanging("Appointments_Regarding");
                this.SetRelatedEntities<ServiceAppointment>("mcs_message_ServiceAppointments", null, value);
                this.OnPropertyChanged("Appointments_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_message_Tasks
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_Tasks")]
        public System.Collections.Generic.IEnumerable<Task> Tasks_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Task>("mcs_message_Tasks", null);
            }

            set
            {
                this.OnPropertyChanging("Tasks_Regarding");
                this.SetRelatedEntities<Task>("mcs_message_Tasks", null, value);
                this.OnPropertyChanged("Tasks_Regarding");
            }
        }

        /// <summary>
        /// 1:N mcs_message_UserEntityInstanceDatas
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_message_UserEntityInstanceDatas")]
        public System.Collections.Generic.IEnumerable<UserEntityInstanceData> UserEntityInstanceData_ObjectId
        {
            get
            {
                return this.GetRelatedEntities<UserEntityInstanceData>("mcs_message_UserEntityInstanceDatas", null);
            }

            set
            {
                this.OnPropertyChanging("UserEntityInstanceData_ObjectId");
                this.SetRelatedEntities<UserEntityInstanceData>("mcs_message_UserEntityInstanceDatas", null, value);
                this.OnPropertyChanged("UserEntityInstanceData_ObjectId");
            }
        }

        /// <summary>
        /// N:1 business_unit_mcs_message
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_mcs_message")]
        public BusinessUnit Messages_OwningBusinessUnit
        {
            get
            {
                return this.GetRelatedEntity<BusinessUnit>("business_unit_mcs_message", null);
            }
        }

        /// <summary>
        /// N:1 lk_mcs_message_createdby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_mcs_message_createdby")]
        public SystemUser Messages_CreatedBy
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_mcs_message_createdby", null);
            }
        }

        /// <summary>
        /// N:1 lk_mcs_message_createdonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_mcs_message_createdonbehalfby")]
        public SystemUser Messages_CreatedBy_Delegate
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_mcs_message_createdonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 lk_mcs_message_modifiedby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_mcs_message_modifiedby")]
        public SystemUser Messages_ModifiedBy
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_mcs_message_modifiedby", null);
            }
        }

        /// <summary>
        /// N:1 lk_mcs_message_modifiedonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_mcs_message_modifiedonbehalfby")]
        public SystemUser Messages_ModifiedBy_Delegate
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_mcs_message_modifiedonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 mcs_mcs_interface_mcs_message_exceptioninterface
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_exceptioninterface")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_mcs_interface_mcs_message_exceptioninterface")]
        public InterfaceDefinition Messages_ExceptionInterface
        {
            get
            {
                return this.GetRelatedEntity<InterfaceDefinition>("mcs_mcs_interface_mcs_message_exceptioninterface", null);
            }

            set
            {
                this.OnPropertyChanging("Messages_ExceptionInterface");
                this.SetRelatedEntity<InterfaceDefinition>("mcs_mcs_interface_mcs_message_exceptioninterface", null, value);
                this.OnPropertyChanged("Messages_ExceptionInterface");
            }
        }

        /// <summary>
        /// N:1 mcs_mcs_interfacemessagetype_mcs_message_messagetype
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_messagetype")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_mcs_interfacemessagetype_mcs_message_messagetype")]
        public InterfaceMessages Messages_MessageType
        {
            get
            {
                return this.GetRelatedEntity<InterfaceMessages>("mcs_mcs_interfacemessagetype_mcs_message_messagetype", null);
            }

            set
            {
                this.OnPropertyChanging("Messages_MessageType");
                this.SetRelatedEntity<InterfaceMessages>("mcs_mcs_interfacemessagetype_mcs_message_messagetype", null, value);
                this.OnPropertyChanged("Messages_MessageType");
            }
        }

        /// <summary>
        /// N:1 mcs_mcs_message_mcs_message
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mcs_relatedmessageid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mcs_mcs_message_mcs_message", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
        public Message Messages_RelatedMessageID_Referencing
        {
            get
            {
                return this.GetRelatedEntity<Message>("mcs_mcs_message_mcs_message", Microsoft.Xrm.Sdk.EntityRole.Referencing);
            }

            set
            {
                this.OnPropertyChanging("Messages_RelatedMessageID_Referencing");
                this.SetRelatedEntity<Message>("mcs_mcs_message_mcs_message", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
                this.OnPropertyChanged("Messages_RelatedMessageID_Referencing");
            }
        }

        /// <summary>
        /// N:1 team_mcs_message
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_mcs_message")]
        public Team Messages_OwningTeam
        {
            get
            {
                return this.GetRelatedEntity<Team>("team_mcs_message", null);
            }
        }

        /// <summary>
        /// N:1 user_mcs_message
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_mcs_message")]
        public SystemUser Messages_OwningUser
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("user_mcs_message", null);
            }
        }
    }
}