//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using VA.TMP.DataModel.OptionSets;

namespace VA.TMP.DataModel
{
    /// <summary>
    /// Quote that has been accepted.
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("salesorder")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public partial class Order : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Default Constructor.
        /// </summary>
        public Order(): base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "salesorder";
        public const string EntityLogicalCollectionName = "salesorders";
        public const string EntitySetName = "salesorders";
        public const int EntityTypeCode = 1088;
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        private void OnPropertyChanging(string propertyName)
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Shows the parent account related to the record. This information is used to link the sales order to the account selected in the Customer field for reporting and analytics.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accountid")]
        public Microsoft.Xrm.Sdk.EntityReference Account
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("accountid");
            }
        }

        /// <summary>
        /// Unique identifier of the billing address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_addressid")]
        public System.Nullable<System.Guid> BillToAddressID
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("billto_addressid");
            }

            set
            {
                this.OnPropertyChanging("BillToAddressID");
                this.SetAttributeValue("billto_addressid", value);
                this.OnPropertyChanged("BillToAddressID");
            }
        }

        /// <summary>
        /// Type the city for the customer's billing address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_city")]
        public string BillToCity
        {
            get
            {
                return this.GetAttributeValue<string>("billto_city");
            }

            set
            {
                this.OnPropertyChanging("BillToCity");
                this.SetAttributeValue("billto_city", value);
                this.OnPropertyChanged("BillToCity");
            }
        }

        /// <summary>
        /// Shows the complete Bill To address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_composite")]
        public string BillToAddress
        {
            get
            {
                return this.GetAttributeValue<string>("billto_composite");
            }
        }

        /// <summary>
        /// Type the primary contact name at the customer's billing address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_contactname")]
        public string BillToContactName
        {
            get
            {
                return this.GetAttributeValue<string>("billto_contactname");
            }

            set
            {
                this.OnPropertyChanging("BillToContactName");
                this.SetAttributeValue("billto_contactname", value);
                this.OnPropertyChanged("BillToContactName");
            }
        }

        /// <summary>
        /// Type the country or region for the customer's billing address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_country")]
        public string BillToCountry_Region
        {
            get
            {
                return this.GetAttributeValue<string>("billto_country");
            }

            set
            {
                this.OnPropertyChanging("BillToCountry_Region");
                this.SetAttributeValue("billto_country", value);
                this.OnPropertyChanged("BillToCountry_Region");
            }
        }

        /// <summary>
        /// Type the fax number for the customer's billing address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_fax")]
        public string BillToFax
        {
            get
            {
                return this.GetAttributeValue<string>("billto_fax");
            }

            set
            {
                this.OnPropertyChanging("BillToFax");
                this.SetAttributeValue("billto_fax", value);
                this.OnPropertyChanged("BillToFax");
            }
        }

        /// <summary>
        /// Type the first line of the customer's billing address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line1")]
        public string BillToStreet1
        {
            get
            {
                return this.GetAttributeValue<string>("billto_line1");
            }

            set
            {
                this.OnPropertyChanging("BillToStreet1");
                this.SetAttributeValue("billto_line1", value);
                this.OnPropertyChanged("BillToStreet1");
            }
        }

        /// <summary>
        /// Type the second line of the customer's billing address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line2")]
        public string BillToStreet2
        {
            get
            {
                return this.GetAttributeValue<string>("billto_line2");
            }

            set
            {
                this.OnPropertyChanging("BillToStreet2");
                this.SetAttributeValue("billto_line2", value);
                this.OnPropertyChanged("BillToStreet2");
            }
        }

        /// <summary>
        /// Type the third line of the billing address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line3")]
        public string BillToStreet3
        {
            get
            {
                return this.GetAttributeValue<string>("billto_line3");
            }

            set
            {
                this.OnPropertyChanging("BillToStreet3");
                this.SetAttributeValue("billto_line3", value);
                this.OnPropertyChanged("BillToStreet3");
            }
        }

        /// <summary>
        /// Type a name for the customer's billing address, such as "Headquarters" or "Field office", to identify the address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_name")]
        public string BillToName
        {
            get
            {
                return this.GetAttributeValue<string>("billto_name");
            }

            set
            {
                this.OnPropertyChanging("BillToName");
                this.SetAttributeValue("billto_name", value);
                this.OnPropertyChanged("BillToName");
            }
        }

        /// <summary>
        /// Type the ZIP Code or postal code for the billing address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_postalcode")]
        public string BillToZIP_PostalCode
        {
            get
            {
                return this.GetAttributeValue<string>("billto_postalcode");
            }

            set
            {
                this.OnPropertyChanging("BillToZIP_PostalCode");
                this.SetAttributeValue("billto_postalcode", value);
                this.OnPropertyChanged("BillToZIP_PostalCode");
            }
        }

        /// <summary>
        /// Type the state or province for the billing address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_stateorprovince")]
        public string BillToState_Province
        {
            get
            {
                return this.GetAttributeValue<string>("billto_stateorprovince");
            }

            set
            {
                this.OnPropertyChanging("BillToState_Province");
                this.SetAttributeValue("billto_stateorprovince", value);
                this.OnPropertyChanged("BillToState_Province");
            }
        }

        /// <summary>
        /// Type the phone number for the customer's billing address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_telephone")]
        public string BillToPhone
        {
            get
            {
                return this.GetAttributeValue<string>("billto_telephone");
            }

            set
            {
                this.OnPropertyChanging("BillToPhone");
                this.SetAttributeValue("billto_telephone", value);
                this.OnPropertyChanged("BillToPhone");
            }
        }

        /// <summary>
        /// campaign_orders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("campaignid")]
        public Microsoft.Xrm.Sdk.EntityReference SourceCampaign
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("campaignid");
            }

            set
            {
                this.OnPropertyChanging("SourceCampaign");
                this.SetAttributeValue("campaignid", value);
                this.OnPropertyChanged("SourceCampaign");
            }
        }

        /// <summary>
        /// Shows the parent contact related to the record. This information is used to link the contract to the contact selected in the Customer field for reporting and analytics.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contactid")]
        public Microsoft.Xrm.Sdk.EntityReference Contact
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contactid");
            }
        }

        /// <summary>
        /// lk_salesorderbase_createdby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// lk_salesorder_createdonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy_Delegate
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// order_customer_contacts
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
        public Microsoft.Xrm.Sdk.EntityReference Customer
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("customerid");
            }

            set
            {
                this.OnPropertyChanging("Customer");
                this.SetAttributeValue("customerid", value);
                this.OnPropertyChanged("Customer");
            }
        }

        /// <summary>
        /// Enter the date that all or part of the order was shipped to the customer.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("datefulfilled")]
        public System.Nullable<System.DateTime> DateFulfilled
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("datefulfilled");
            }

            set
            {
                this.OnPropertyChanging("DateFulfilled");
                this.SetAttributeValue("datefulfilled", value);
                this.OnPropertyChanged("DateFulfilled");
            }
        }

        /// <summary>
        /// Type additional information to describe the order, such as the products or services offered or details about the customer's product preferences.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
        public string Description
        {
            get
            {
                return this.GetAttributeValue<string>("description");
            }

            set
            {
                this.OnPropertyChanging("Description");
                this.SetAttributeValue("description", value);
                this.OnPropertyChanged("Description");
            }
        }

        /// <summary>
        /// Type the discount amount for the order if the customer is eligible for special savings.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountamount")]
        public Microsoft.Xrm.Sdk.Money OrderDiscountAmount
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("discountamount");
            }

            set
            {
                this.OnPropertyChanging("OrderDiscountAmount");
                this.SetAttributeValue("discountamount", value);
                this.OnPropertyChanged("OrderDiscountAmount");
            }
        }

        /// <summary>
        /// Shows the Order Discount field converted to the system's default base currency for reporting purposes. The calculation uses the exchange rate specified in the Currencies area.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountamount_base")]
        public Microsoft.Xrm.Sdk.Money OrderDiscountAmount_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("discountamount_base");
            }
        }

        /// <summary>
        /// Type the discount rate that should be applied to the Detail Amount field to include additional savings for the customer in the order.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountpercentage")]
        public System.Nullable<decimal> OrderDiscount_
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("discountpercentage");
            }

            set
            {
                this.OnPropertyChanging("OrderDiscount_");
                this.SetAttributeValue("discountpercentage", value);
                this.OnPropertyChanged("OrderDiscount_");
            }
        }

        /// <summary>
        /// The primary email address for the entity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailaddress")]
        public string EmailAddress
        {
            get
            {
                return this.GetAttributeValue<string>("emailaddress");
            }

            set
            {
                this.OnPropertyChanging("EmailAddress");
                this.SetAttributeValue("emailaddress", value);
                this.OnPropertyChanged("EmailAddress");
            }
        }

        /// <summary>
        /// The default image for the entity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage")]
        public byte[] EntityImage
        {
            get
            {
                return this.GetAttributeValue<byte[]>("entityimage");
            }

            set
            {
                this.OnPropertyChanging("EntityImage");
                this.SetAttributeValue("entityimage", value);
                this.OnPropertyChanged("EntityImage");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_timestamp")]
        public System.Nullable<long> EntityImage_Timestamp
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
            }
        }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_url")]
        public string EntityImage_URL
        {
            get
            {
                return this.GetAttributeValue<string>("entityimage_url");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimageid")]
        public System.Nullable<System.Guid> EntityImageId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
            }
        }

        /// <summary>
        /// Shows the conversion rate of the record's currency. The exchange rate is used to convert all money fields in the record from the local currency to the system's default currency.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
        public System.Nullable<decimal> ExchangeRate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
            }
        }

        /// <summary>
        /// Type the cost of freight or shipping for the products included in the order for use in calculating the Total Amount field.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freightamount")]
        public Microsoft.Xrm.Sdk.Money FreightAmount
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("freightamount");
            }

            set
            {
                this.OnPropertyChanging("FreightAmount");
                this.SetAttributeValue("freightamount", value);
                this.OnPropertyChanged("FreightAmount");
            }
        }

        /// <summary>
        /// Shows the Freight Amount field converted to the system's default base currency for reporting purposes. The calculation uses the exchange rate specified in the Currencies area.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freightamount_base")]
        public Microsoft.Xrm.Sdk.Money FreightAmount_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("freightamount_base");
            }
        }

        /// <summary>
        /// Select the freight terms to make sure shipping charges are processed correctly.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freighttermscode")]
        public System.Nullable<Order_FreightTerms> FreightTerms
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("freighttermscode");
                if ((optionSet != null))
                {
                    return ((Order_FreightTerms)(System.Enum.ToObject(typeof(Order_FreightTerms), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("FreightTerms");
                if ((value == null))
                {
                    this.SetAttributeValue("freighttermscode", null);
                }
                else
                {
                    this.SetAttributeValue("freighttermscode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("FreightTerms");
            }
        }

        /// <summary>
        /// Unique identifier of the data import or data migration that created this record.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }

            set
            {
                this.OnPropertyChanging("ImportSequenceNumber");
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Select whether prices specified on the invoice are locked from any further updates.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ispricelocked")]
        public System.Nullable<bool> PricesLocked
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("ispricelocked");
            }

            set
            {
                this.OnPropertyChanging("PricesLocked");
                this.SetAttributeValue("ispricelocked", value);
                this.OnPropertyChanged("PricesLocked");
            }
        }

        /// <summary>
        /// Enter the date and time when the order was last submitted to an accounting or ERP system for processing.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastbackofficesubmit")]
        public System.Nullable<System.DateTime> LastSubmittedToBackOffice
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastbackofficesubmit");
            }

            set
            {
                this.OnPropertyChanging("LastSubmittedToBackOffice");
                this.SetAttributeValue("lastbackofficesubmit", value);
                this.OnPropertyChanged("LastSubmittedToBackOffice");
            }
        }

        /// <summary>
        /// Contains the date time stamp of the last on hold time.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastonholdtime")]
        public System.Nullable<System.DateTime> LastOnHoldTime
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastonholdtime");
            }

            set
            {
                this.OnPropertyChanging("LastOnHoldTime");
                this.SetAttributeValue("lastonholdtime", value);
                this.OnPropertyChanged("LastOnHoldTime");
            }
        }

        /// <summary>
        /// lk_salesorderbase_modifiedby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Shows the date and time when the record was last updated. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// lk_salesorder_modifiedonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy_Delegate
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// Type a descriptive name for the order.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
        public string Name
        {
            get
            {
                return this.GetAttributeValue<string>("name");
            }

            set
            {
                this.OnPropertyChanging("Name");
                this.SetAttributeValue("name", value);
                this.OnPropertyChanged("Name");
            }
        }

        /// <summary>
        /// Shows the duration in minutes for which the order was on hold.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("onholdtime")]
        public System.Nullable<int> OnHoldTime_Minutes
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("onholdtime");
            }
        }

        /// <summary>
        /// opportunity_sales_orders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opportunityid")]
        public Microsoft.Xrm.Sdk.EntityReference Opportunity
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("opportunityid");
            }

            set
            {
                this.OnPropertyChanging("Opportunity");
                this.SetAttributeValue("opportunityid", value);
                this.OnPropertyChanged("Opportunity");
            }
        }

        /// <summary>
        /// Shows the order number for customer reference and to use in search. The number cannot be modified.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ordernumber")]
        public string OrderID
        {
            get
            {
                return this.GetAttributeValue<string>("ordernumber");
            }

            set
            {
                this.OnPropertyChanging("OrderID");
                this.SetAttributeValue("ordernumber", value);
                this.OnPropertyChanged("OrderID");
            }
        }

        /// <summary>
        /// Date and time that the record was migrated.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> RecordCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }

            set
            {
                this.OnPropertyChanging("RecordCreatedOn");
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("RecordCreatedOn");
            }
        }

        /// <summary>
        /// owner_salesorders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
        public Microsoft.Xrm.Sdk.EntityReference Owner
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
            }

            set
            {
                this.OnPropertyChanging("Owner");
                this.SetAttributeValue("ownerid", value);
                this.OnPropertyChanged("Owner");
            }
        }

        /// <summary>
        /// business_unit_orders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// team_orders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        public Microsoft.Xrm.Sdk.EntityReference OwningTeam
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// system_user_orders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        public Microsoft.Xrm.Sdk.EntityReference OwningUser
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// Select the payment terms to indicate when the customer needs to pay the total amount.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("paymenttermscode")]
        public System.Nullable<Order_PaymentTerms> PaymentTerms
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("paymenttermscode");
                if ((optionSet != null))
                {
                    return ((Order_PaymentTerms)(System.Enum.ToObject(typeof(Order_PaymentTerms), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("PaymentTerms");
                if ((value == null))
                {
                    this.SetAttributeValue("paymenttermscode", null);
                }
                else
                {
                    this.SetAttributeValue("paymenttermscode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("PaymentTerms");
            }
        }

        /// <summary>
        /// price_level_orders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricelevelid")]
        public Microsoft.Xrm.Sdk.EntityReference PriceList
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("pricelevelid");
            }

            set
            {
                this.OnPropertyChanging("PriceList");
                this.SetAttributeValue("pricelevelid", value);
                this.OnPropertyChanged("PriceList");
            }
        }

        /// <summary>
        /// Select the type of pricing error, such as a missing or invalid product, or missing quantity.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricingerrorcode")]
        public System.Nullable<PricingError> PricingError
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("pricingerrorcode");
                if ((optionSet != null))
                {
                    return ((PricingError)(System.Enum.ToObject(typeof(PricingError), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("PricingError");
                if ((value == null))
                {
                    this.SetAttributeValue("pricingerrorcode", null);
                }
                else
                {
                    this.SetAttributeValue("pricingerrorcode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("PricingError");
            }
        }

        /// <summary>
        /// Select the priority so that preferred customers or critical issues are handled quickly.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("prioritycode")]
        public System.Nullable<Order_Priority> Priority
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("prioritycode");
                if ((optionSet != null))
                {
                    return ((Order_Priority)(System.Enum.ToObject(typeof(Order_Priority), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("Priority");
                if ((value == null))
                {
                    this.SetAttributeValue("prioritycode", null);
                }
                else
                {
                    this.SetAttributeValue("prioritycode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("Priority");
            }
        }

        /// <summary>
        /// Shows the ID of the process.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
        public System.Nullable<System.Guid> Process
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
            }

            set
            {
                this.OnPropertyChanging("Process");
                this.SetAttributeValue("processid", value);
                this.OnPropertyChanged("Process");
            }
        }

        /// <summary>
        /// quote_orders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quoteid")]
        public Microsoft.Xrm.Sdk.EntityReference Quote
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("quoteid");
            }

            set
            {
                this.OnPropertyChanging("Quote");
                this.SetAttributeValue("quoteid", value);
                this.OnPropertyChanged("Quote");
            }
        }

        /// <summary>
        /// Enter the delivery date requested by the customer for all products in the order.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requestdeliveryby")]
        public System.Nullable<System.DateTime> RequestedDeliveryDate
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("requestdeliveryby");
            }

            set
            {
                this.OnPropertyChanging("RequestedDeliveryDate");
                this.SetAttributeValue("requestdeliveryby", value);
                this.OnPropertyChanged("RequestedDeliveryDate");
            }
        }

        /// <summary>
        /// Unique identifier of the order.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderid")]
        public System.Nullable<System.Guid> OrderId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("salesorderid");
            }

            set
            {
                this.OnPropertyChanging("OrderId");
                this.SetAttributeValue("salesorderid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }

                this.OnPropertyChanged("OrderId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }

            set
            {
                this.OrderId = value;
            }
        }

        /// <summary>
        /// Select a shipping method for deliveries sent to this address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shippingmethodcode")]
        public System.Nullable<Order_ShippingMethod> ShippingMethod
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("shippingmethodcode");
                if ((optionSet != null))
                {
                    return ((Order_ShippingMethod)(System.Enum.ToObject(typeof(Order_ShippingMethod), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("ShippingMethod");
                if ((value == null))
                {
                    this.SetAttributeValue("shippingmethodcode", null);
                }
                else
                {
                    this.SetAttributeValue("shippingmethodcode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("ShippingMethod");
            }
        }

        /// <summary>
        /// Unique identifier of the shipping address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_addressid")]
        public System.Nullable<System.Guid> ShipToAddressID
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("shipto_addressid");
            }

            set
            {
                this.OnPropertyChanging("ShipToAddressID");
                this.SetAttributeValue("shipto_addressid", value);
                this.OnPropertyChanged("ShipToAddressID");
            }
        }

        /// <summary>
        /// Type the city for the customer's shipping address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_city")]
        public string ShipToCity
        {
            get
            {
                return this.GetAttributeValue<string>("shipto_city");
            }

            set
            {
                this.OnPropertyChanging("ShipToCity");
                this.SetAttributeValue("shipto_city", value);
                this.OnPropertyChanged("ShipToCity");
            }
        }

        /// <summary>
        /// Shows the complete Ship To address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_composite")]
        public string ShipToAddress
        {
            get
            {
                return this.GetAttributeValue<string>("shipto_composite");
            }
        }

        /// <summary>
        /// Type the primary contact name at the customer's shipping address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_contactname")]
        public string ShipToContactName
        {
            get
            {
                return this.GetAttributeValue<string>("shipto_contactname");
            }

            set
            {
                this.OnPropertyChanging("ShipToContactName");
                this.SetAttributeValue("shipto_contactname", value);
                this.OnPropertyChanged("ShipToContactName");
            }
        }

        /// <summary>
        /// Type the country or region for the customer's shipping address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_country")]
        public string ShipToCountry_Region
        {
            get
            {
                return this.GetAttributeValue<string>("shipto_country");
            }

            set
            {
                this.OnPropertyChanging("ShipToCountry_Region");
                this.SetAttributeValue("shipto_country", value);
                this.OnPropertyChanged("ShipToCountry_Region");
            }
        }

        /// <summary>
        /// Type the fax number for the customer's shipping address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_fax")]
        public string ShipToFax
        {
            get
            {
                return this.GetAttributeValue<string>("shipto_fax");
            }

            set
            {
                this.OnPropertyChanging("ShipToFax");
                this.SetAttributeValue("shipto_fax", value);
                this.OnPropertyChanged("ShipToFax");
            }
        }

        /// <summary>
        /// Select the freight terms to make sure shipping orders are processed correctly.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_freighttermscode")]
        public System.Nullable<Order_ShipToFreightTerms> ShipToFreightTerms
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("shipto_freighttermscode");
                if ((optionSet != null))
                {
                    return ((Order_ShipToFreightTerms)(System.Enum.ToObject(typeof(Order_ShipToFreightTerms), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("ShipToFreightTerms");
                if ((value == null))
                {
                    this.SetAttributeValue("shipto_freighttermscode", null);
                }
                else
                {
                    this.SetAttributeValue("shipto_freighttermscode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("ShipToFreightTerms");
            }
        }

        /// <summary>
        /// Type the first line of the customer's shipping address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line1")]
        public string ShipToStreet1
        {
            get
            {
                return this.GetAttributeValue<string>("shipto_line1");
            }

            set
            {
                this.OnPropertyChanging("ShipToStreet1");
                this.SetAttributeValue("shipto_line1", value);
                this.OnPropertyChanged("ShipToStreet1");
            }
        }

        /// <summary>
        /// Type the second line of the customer's shipping address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line2")]
        public string ShipToStreet2
        {
            get
            {
                return this.GetAttributeValue<string>("shipto_line2");
            }

            set
            {
                this.OnPropertyChanging("ShipToStreet2");
                this.SetAttributeValue("shipto_line2", value);
                this.OnPropertyChanged("ShipToStreet2");
            }
        }

        /// <summary>
        /// Type the third line of the shipping address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line3")]
        public string ShipToStreet3
        {
            get
            {
                return this.GetAttributeValue<string>("shipto_line3");
            }

            set
            {
                this.OnPropertyChanging("ShipToStreet3");
                this.SetAttributeValue("shipto_line3", value);
                this.OnPropertyChanged("ShipToStreet3");
            }
        }

        /// <summary>
        /// Type a name for the customer's shipping address, such as "Headquarters" or "Field office",  to identify the address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_name")]
        public string ShipToName
        {
            get
            {
                return this.GetAttributeValue<string>("shipto_name");
            }

            set
            {
                this.OnPropertyChanging("ShipToName");
                this.SetAttributeValue("shipto_name", value);
                this.OnPropertyChanged("ShipToName");
            }
        }

        /// <summary>
        /// Type the ZIP Code or postal code for the shipping address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_postalcode")]
        public string ShipToZIP_PostalCode
        {
            get
            {
                return this.GetAttributeValue<string>("shipto_postalcode");
            }

            set
            {
                this.OnPropertyChanging("ShipToZIP_PostalCode");
                this.SetAttributeValue("shipto_postalcode", value);
                this.OnPropertyChanged("ShipToZIP_PostalCode");
            }
        }

        /// <summary>
        /// Type the state or province for the shipping address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_stateorprovince")]
        public string ShipToState_Province
        {
            get
            {
                return this.GetAttributeValue<string>("shipto_stateorprovince");
            }

            set
            {
                this.OnPropertyChanging("ShipToState_Province");
                this.SetAttributeValue("shipto_stateorprovince", value);
                this.OnPropertyChanged("ShipToState_Province");
            }
        }

        /// <summary>
        /// Type the phone number for the customer's shipping address.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_telephone")]
        public string ShipToPhone
        {
            get
            {
                return this.GetAttributeValue<string>("shipto_telephone");
            }

            set
            {
                this.OnPropertyChanging("ShipToPhone");
                this.SetAttributeValue("shipto_telephone", value);
                this.OnPropertyChanged("ShipToPhone");
            }
        }

        /// <summary>
        /// Skip Price Calculation
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("skippricecalculation")]
        public System.Nullable<SkipPriceCalculationOptionSet> SkipPriceCalculation_ForInternalUse
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("skippricecalculation");
                if ((optionSet != null))
                {
                    return ((SkipPriceCalculationOptionSet)(System.Enum.ToObject(typeof(SkipPriceCalculationOptionSet), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("SkipPriceCalculation_ForInternalUse");
                if ((value == null))
                {
                    this.SetAttributeValue("skippricecalculation", null);
                }
                else
                {
                    this.SetAttributeValue("skippricecalculation", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("SkipPriceCalculation_ForInternalUse");
            }
        }

        /// <summary>
        /// manualsla_salesorder
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaid")]
        public Microsoft.Xrm.Sdk.EntityReference SLA
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slaid");
            }

            set
            {
                this.OnPropertyChanging("SLA");
                this.SetAttributeValue("slaid", value);
                this.OnPropertyChanged("SLA");
            }
        }

        /// <summary>
        /// sla_salesorder
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slainvokedid")]
        public Microsoft.Xrm.Sdk.EntityReference LastSLAApplied
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slainvokedid");
            }
        }

        /// <summary>
        /// processstage_salesorders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
        public System.Nullable<System.Guid> ProcessStage
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
            }

            set
            {
                this.OnPropertyChanging("ProcessStage");
                this.SetAttributeValue("stageid", value);
                this.OnPropertyChanged("ProcessStage");
            }
        }

        /// <summary>
        /// Shows whether the order is active, submitted, fulfilled, canceled, or invoiced. Only active orders can be edited.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public System.Nullable<Order_Status> Status
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
                if ((optionSet != null))
                {
                    return ((Order_Status)(System.Enum.ToObject(typeof(Order_Status), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("Status");
                if ((value == null))
                {
                    this.SetAttributeValue("statecode", null);
                }
                else
                {
                    this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("Status");
            }
        }

        /// <summary>
        /// Select the order's status.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public System.Nullable<Order_StatusReason> StatusReason
        {
            get
            {
                Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
                if ((optionSet != null))
                {
                    return ((Order_StatusReason)(System.Enum.ToObject(typeof(Order_StatusReason), optionSet.Value)));
                }
                else
                {
                    return null;
                }
            }

            set
            {
                this.OnPropertyChanging("StatusReason");
                if ((value == null))
                {
                    this.SetAttributeValue("statuscode", null);
                }
                else
                {
                    this.SetAttributeValue("statuscode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
                }

                this.OnPropertyChanged("StatusReason");
            }
        }

        /// <summary>
        /// Enter the date when the order was submitted to the fulfillment or shipping center.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("submitdate")]
        public System.Nullable<System.DateTime> DateSubmitted
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("submitdate");
            }

            set
            {
                this.OnPropertyChanging("DateSubmitted");
                this.SetAttributeValue("submitdate", value);
                this.OnPropertyChanged("DateSubmitted");
            }
        }

        /// <summary>
        /// Type the code for the submitted status in the fulfillment or shipping center system.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("submitstatus")]
        public System.Nullable<int> SubmittedStatus
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("submitstatus");
            }

            set
            {
                this.OnPropertyChanging("SubmittedStatus");
                this.SetAttributeValue("submitstatus", value);
                this.OnPropertyChanged("SubmittedStatus");
            }
        }

        /// <summary>
        /// Type additional details or notes about the order for the fulfillment or shipping center.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("submitstatusdescription")]
        public string SubmittedStatusDescription
        {
            get
            {
                return this.GetAttributeValue<string>("submitstatusdescription");
            }

            set
            {
                this.OnPropertyChanging("SubmittedStatusDescription");
                this.SetAttributeValue("submitstatusdescription", value);
                this.OnPropertyChanged("SubmittedStatusDescription");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }

            set
            {
                this.OnPropertyChanging("TimeZoneRuleVersionNumber");
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Shows the total amount due, calculated as the sum of the products, discounts, freight, and taxes for the order.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamount")]
        public Microsoft.Xrm.Sdk.Money TotalAmount
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamount");
            }

            set
            {
                this.OnPropertyChanging("TotalAmount");
                this.SetAttributeValue("totalamount", value);
                this.OnPropertyChanged("TotalAmount");
            }
        }

        /// <summary>
        /// Shows the Total Amount field converted to the system's default base currency for reporting purposes. The calculation uses the exchange rate specified in the Currencies area.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamount_base")]
        public Microsoft.Xrm.Sdk.Money TotalAmount_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamount_base");
            }
        }

        /// <summary>
        /// Shows the total product amount for the order, minus any discounts. This value is added to freight and tax amounts in the calculation for the total amount due for the order.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamountlessfreight")]
        public Microsoft.Xrm.Sdk.Money TotalPreFreightAmount
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamountlessfreight");
            }

            set
            {
                this.OnPropertyChanging("TotalPreFreightAmount");
                this.SetAttributeValue("totalamountlessfreight", value);
                this.OnPropertyChanged("TotalPreFreightAmount");
            }
        }

        /// <summary>
        /// Shows the Pre-Freight Amount field converted to the system's default base currency for reporting purposes. The calculation uses the exchange rate specified in the Currencies area.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamountlessfreight_base")]
        public Microsoft.Xrm.Sdk.Money TotalPreFreightAmount_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamountlessfreight_base");
            }
        }

        /// <summary>
        /// Shows the total discount amount, based on the discount price and rate entered on the order.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaldiscountamount")]
        public Microsoft.Xrm.Sdk.Money TotalDiscountAmount
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaldiscountamount");
            }

            set
            {
                this.OnPropertyChanging("TotalDiscountAmount");
                this.SetAttributeValue("totaldiscountamount", value);
                this.OnPropertyChanged("TotalDiscountAmount");
            }
        }

        /// <summary>
        /// Shows the Total Discount Amount field converted to the system's default base currency for reporting purposes. The calculation uses the exchange rate specified in the Currencies area.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaldiscountamount_base")]
        public Microsoft.Xrm.Sdk.Money TotalDiscountAmount_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaldiscountamount_base");
            }
        }

        /// <summary>
        /// Shows the sum of all existing and write-in products included on the order, based on the specified price list and quantities.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemamount")]
        public Microsoft.Xrm.Sdk.Money TotalDetailAmount
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemamount");
            }

            set
            {
                this.OnPropertyChanging("TotalDetailAmount");
                this.SetAttributeValue("totallineitemamount", value);
                this.OnPropertyChanged("TotalDetailAmount");
            }
        }

        /// <summary>
        /// Shows the Detail Amount field converted to the system's default base currency. The calculation uses the exchange rate specified in the Currencies area.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemamount_base")]
        public Microsoft.Xrm.Sdk.Money TotalDetailAmount_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemamount_base");
            }
        }

        /// <summary>
        /// Shows the total of the Manual Discount amounts specified on all products included in the order. This value is reflected in the Detail Amount field on the order and is added to any discount amount or rate specified on the order.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemdiscountamount")]
        public Microsoft.Xrm.Sdk.Money TotalLineItemDiscountAmount
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemdiscountamount");
            }

            set
            {
                this.OnPropertyChanging("TotalLineItemDiscountAmount");
                this.SetAttributeValue("totallineitemdiscountamount", value);
                this.OnPropertyChanged("TotalLineItemDiscountAmount");
            }
        }

        /// <summary>
        /// Shows the Total Line Item Discount Amount field converted to the system's default base currency for reporting purposes. The calculation uses the exchange rate specified in the Currencies area.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemdiscountamount_base")]
        public Microsoft.Xrm.Sdk.Money TotalLineItemDiscountAmount_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemdiscountamount_base");
            }
        }

        /// <summary>
        /// Shows the Tax amounts specified on all products included in the order, included in the Total Amount due calculation for the order.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaltax")]
        public Microsoft.Xrm.Sdk.Money TotalTax
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaltax");
            }

            set
            {
                this.OnPropertyChanging("TotalTax");
                this.SetAttributeValue("totaltax", value);
                this.OnPropertyChanged("TotalTax");
            }
        }

        /// <summary>
        /// Shows the Total Tax field converted to the system's default base currency for reporting purposes. The calculation uses the exchange rate specified in the Currencies area.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaltax_base")]
        public Microsoft.Xrm.Sdk.Money TotalTax_Base
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaltax_base");
            }
        }

        /// <summary>
        /// transactioncurrency_salesorder
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
        public Microsoft.Xrm.Sdk.EntityReference Currency
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
            }

            set
            {
                this.OnPropertyChanging("Currency");
                this.SetAttributeValue("transactioncurrencyid", value);
                this.OnPropertyChanged("Currency");
            }
        }

        /// <summary>
        /// For internal use only.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
        public string TraversedPath
        {
            get
            {
                return this.GetAttributeValue<string>("traversedpath");
            }

            set
            {
                this.OnPropertyChanging("TraversedPath");
                this.SetAttributeValue("traversedpath", value);
                this.OnPropertyChanged("TraversedPath");
            }
        }

        /// <summary>
        /// Time zone code that was in use when the record was created.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }

            set
            {
                this.OnPropertyChanging("UTCConversionTimeZoneCode");
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// Version number of the order.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        /// <summary>
        /// Select whether the products included in the order should be shipped to the specified address or held until the customer calls with further pick-up or delivery instructions.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("willcall")]
        public System.Nullable<bool> ShipTo
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("willcall");
            }

            set
            {
                this.OnPropertyChanging("ShipTo");
                this.SetAttributeValue("willcall", value);
                this.OnPropertyChanged("ShipTo");
            }
        }

        /// <summary>
        /// 1:N msdyn_playbookinstance_salesorder
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_playbookinstance_salesorder")]
        public System.Collections.Generic.IEnumerable<Playbook> Playbooks_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Playbook>("msdyn_playbookinstance_salesorder", null);
            }

            set
            {
                this.OnPropertyChanging("Playbooks_Regarding");
                this.SetRelatedEntities<Playbook>("msdyn_playbookinstance_salesorder", null, value);
                this.OnPropertyChanged("Playbooks_Regarding");
            }
        }

        /// <summary>
        /// 1:N order_invoices
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("order_invoices")]
        public System.Collections.Generic.IEnumerable<Invoice> Invoices_Order
        {
            get
            {
                return this.GetRelatedEntities<Invoice>("order_invoices", null);
            }

            set
            {
                this.OnPropertyChanging("Invoices_Order");
                this.SetRelatedEntities<Invoice>("order_invoices", null, value);
                this.OnPropertyChanged("Invoices_Order");
            }
        }

        /// <summary>
        /// 1:N salesorder_activity_parties
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesorder_activity_parties")]
        public System.Collections.Generic.IEnumerable<ActivityParty> ActivityParties_Party
        {
            get
            {
                return this.GetRelatedEntities<ActivityParty>("salesorder_activity_parties", null);
            }

            set
            {
                this.OnPropertyChanging("ActivityParties_Party");
                this.SetRelatedEntities<ActivityParty>("salesorder_activity_parties", null, value);
                this.OnPropertyChanged("ActivityParties_Party");
            }
        }

        /// <summary>
        /// 1:N SalesOrder_ActivityPointers
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrder_ActivityPointers")]
        public System.Collections.Generic.IEnumerable<ActivityPointer> Activities_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ActivityPointer>("SalesOrder_ActivityPointers", null);
            }

            set
            {
                this.OnPropertyChanging("Activities_Regarding");
                this.SetRelatedEntities<ActivityPointer>("SalesOrder_ActivityPointers", null, value);
                this.OnPropertyChanged("Activities_Regarding");
            }
        }

        /// <summary>
        /// 1:N SalesOrder_Annotation
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrder_Annotation")]
        public System.Collections.Generic.IEnumerable<Annotation> Notes_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Annotation>("SalesOrder_Annotation", null);
            }

            set
            {
                this.OnPropertyChanging("Notes_Regarding");
                this.SetRelatedEntities<Annotation>("SalesOrder_Annotation", null, value);
                this.OnPropertyChanged("Notes_Regarding");
            }
        }

        /// <summary>
        /// 1:N SalesOrder_Appointments
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrder_Appointments")]
        public System.Collections.Generic.IEnumerable<Appointment> ReserveResources_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Appointment>("SalesOrder_Appointments", null);
            }

            set
            {
                this.OnPropertyChanging("ReserveResources_Regarding");
                this.SetRelatedEntities<Appointment>("SalesOrder_Appointments", null, value);
                this.OnPropertyChanged("ReserveResources_Regarding");
            }
        }

        /// <summary>
        /// 1:N SalesOrder_AsyncOperations
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrder_AsyncOperations")]
        public System.Collections.Generic.IEnumerable<SystemJob> SystemJobs_Regarding
        {
            get
            {
                return this.GetRelatedEntities<SystemJob>("SalesOrder_AsyncOperations", null);
            }

            set
            {
                this.OnPropertyChanging("SystemJobs_Regarding");
                this.SetRelatedEntities<SystemJob>("SalesOrder_AsyncOperations", null, value);
                this.OnPropertyChanged("SystemJobs_Regarding");
            }
        }

        /// <summary>
        /// 1:N SalesOrder_BulkDeleteFailures
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrder_BulkDeleteFailures")]
        public System.Collections.Generic.IEnumerable<BulkDeleteFailure> BulkDeleteFailures_Name
        {
            get
            {
                return this.GetRelatedEntities<BulkDeleteFailure>("SalesOrder_BulkDeleteFailures", null);
            }

            set
            {
                this.OnPropertyChanging("BulkDeleteFailures_Name");
                this.SetRelatedEntities<BulkDeleteFailure>("SalesOrder_BulkDeleteFailures", null, value);
                this.OnPropertyChanged("BulkDeleteFailures_Name");
            }
        }

        /// <summary>
        /// 1:N salesorder_connections1
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesorder_connections1")]
        public System.Collections.Generic.IEnumerable<Connection> Connections_ConnectedFrom
        {
            get
            {
                return this.GetRelatedEntities<Connection>("salesorder_connections1", null);
            }

            set
            {
                this.OnPropertyChanging("Connections_ConnectedFrom");
                this.SetRelatedEntities<Connection>("salesorder_connections1", null, value);
                this.OnPropertyChanged("Connections_ConnectedFrom");
            }
        }

        /// <summary>
        /// 1:N salesorder_connections2
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesorder_connections2")]
        public System.Collections.Generic.IEnumerable<Connection> Connections_ConnectedTo
        {
            get
            {
                return this.GetRelatedEntities<Connection>("salesorder_connections2", null);
            }

            set
            {
                this.OnPropertyChanging("Connections_ConnectedTo");
                this.SetRelatedEntities<Connection>("salesorder_connections2", null, value);
                this.OnPropertyChanged("Connections_ConnectedTo");
            }
        }

        /// <summary>
        /// 1:N SalesOrder_Emails
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrder_Emails")]
        public System.Collections.Generic.IEnumerable<Email> EmailMessages_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Email>("SalesOrder_Emails", null);
            }

            set
            {
                this.OnPropertyChanging("EmailMessages_Regarding");
                this.SetRelatedEntities<Email>("SalesOrder_Emails", null, value);
                this.OnPropertyChanged("EmailMessages_Regarding");
            }
        }

        /// <summary>
        /// 1:N SalesOrder_MailboxTrackingFolder
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrder_MailboxTrackingFolder")]
        public System.Collections.Generic.IEnumerable<MailboxAutoTrackingFolder> MailboxAutoTrackingFolders_RegardingObjectId
        {
            get
            {
                return this.GetRelatedEntities<MailboxAutoTrackingFolder>("SalesOrder_MailboxTrackingFolder", null);
            }

            set
            {
                this.OnPropertyChanging("MailboxAutoTrackingFolders_RegardingObjectId");
                this.SetRelatedEntities<MailboxAutoTrackingFolder>("SalesOrder_MailboxTrackingFolder", null, value);
                this.OnPropertyChanged("MailboxAutoTrackingFolders_RegardingObjectId");
            }
        }

        /// <summary>
        /// 1:N salesorder_principalobjectattributeaccess
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesorder_principalobjectattributeaccess")]
        public System.Collections.Generic.IEnumerable<FieldSharing> FieldSharing_EntityInstance
        {
            get
            {
                return this.GetRelatedEntities<FieldSharing>("salesorder_principalobjectattributeaccess", null);
            }

            set
            {
                this.OnPropertyChanging("FieldSharing_EntityInstance");
                this.SetRelatedEntities<FieldSharing>("salesorder_principalobjectattributeaccess", null, value);
                this.OnPropertyChanged("FieldSharing_EntityInstance");
            }
        }

        /// <summary>
        /// 1:N SalesOrder_ProcessSessions
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrder_ProcessSessions")]
        public System.Collections.Generic.IEnumerable<ProcessSession> ProcessSessions_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ProcessSession>("SalesOrder_ProcessSessions", null);
            }

            set
            {
                this.OnPropertyChanging("ProcessSessions_Regarding");
                this.SetRelatedEntities<ProcessSession>("SalesOrder_ProcessSessions", null, value);
                this.OnPropertyChanged("ProcessSessions_Regarding");
            }
        }

        /// <summary>
        /// 1:N SalesOrder_RecurringAppointmentMasters
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrder_RecurringAppointmentMasters")]
        public System.Collections.Generic.IEnumerable<RecurringAppointmentMaster> RecurringReserveResources_Regarding
        {
            get
            {
                return this.GetRelatedEntities<RecurringAppointmentMaster>("SalesOrder_RecurringAppointmentMasters", null);
            }

            set
            {
                this.OnPropertyChanging("RecurringReserveResources_Regarding");
                this.SetRelatedEntities<RecurringAppointmentMaster>("SalesOrder_RecurringAppointmentMasters", null, value);
                this.OnPropertyChanged("RecurringReserveResources_Regarding");
            }
        }

        /// <summary>
        /// 1:N SalesOrder_ServiceAppointments
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrder_ServiceAppointments")]
        public System.Collections.Generic.IEnumerable<ServiceAppointment> Appointments_Regarding
        {
            get
            {
                return this.GetRelatedEntities<ServiceAppointment>("SalesOrder_ServiceAppointments", null);
            }

            set
            {
                this.OnPropertyChanging("Appointments_Regarding");
                this.SetRelatedEntities<ServiceAppointment>("SalesOrder_ServiceAppointments", null, value);
                this.OnPropertyChanged("Appointments_Regarding");
            }
        }

        /// <summary>
        /// 1:N SalesOrder_SyncErrors
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrder_SyncErrors")]
        public System.Collections.Generic.IEnumerable<SyncError> SyncErrors_Record
        {
            get
            {
                return this.GetRelatedEntities<SyncError>("SalesOrder_SyncErrors", null);
            }

            set
            {
                this.OnPropertyChanging("SyncErrors_Record");
                this.SetRelatedEntities<SyncError>("SalesOrder_SyncErrors", null, value);
                this.OnPropertyChanged("SyncErrors_Record");
            }
        }

        /// <summary>
        /// 1:N SalesOrder_Tasks
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrder_Tasks")]
        public System.Collections.Generic.IEnumerable<Task> Tasks_Regarding
        {
            get
            {
                return this.GetRelatedEntities<Task>("SalesOrder_Tasks", null);
            }

            set
            {
                this.OnPropertyChanging("Tasks_Regarding");
                this.SetRelatedEntities<Task>("SalesOrder_Tasks", null, value);
                this.OnPropertyChanged("Tasks_Regarding");
            }
        }

        /// <summary>
        /// 1:N slakpiinstance_salesorder
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("slakpiinstance_salesorder")]
        public System.Collections.Generic.IEnumerable<SLAKPIInstance> SLAKPIInstances_Regarding
        {
            get
            {
                return this.GetRelatedEntities<SLAKPIInstance>("slakpiinstance_salesorder", null);
            }

            set
            {
                this.OnPropertyChanging("SLAKPIInstances_Regarding");
                this.SetRelatedEntities<SLAKPIInstance>("slakpiinstance_salesorder", null, value);
                this.OnPropertyChanged("SLAKPIInstances_Regarding");
            }
        }

        /// <summary>
        /// 1:N userentityinstancedata_salesorder
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("userentityinstancedata_salesorder")]
        public System.Collections.Generic.IEnumerable<UserEntityInstanceData> UserEntityInstanceData_ObjectId
        {
            get
            {
                return this.GetRelatedEntities<UserEntityInstanceData>("userentityinstancedata_salesorder", null);
            }

            set
            {
                this.OnPropertyChanging("UserEntityInstanceData_ObjectId");
                this.SetRelatedEntities<UserEntityInstanceData>("userentityinstancedata_salesorder", null, value);
                this.OnPropertyChanged("UserEntityInstanceData_ObjectId");
            }
        }

        /// <summary>
        /// N:N contactorders_association
        /// </summary>
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("contactorders_association")]
        public System.Collections.Generic.IEnumerable<Contact> Patients
        {
            get
            {
                return this.GetRelatedEntities<Contact>("contactorders_association", null);
            }

            set
            {
                this.OnPropertyChanging("Patients");
                this.SetRelatedEntities<Contact>("contactorders_association", null, value);
                this.OnPropertyChanged("Patients");
            }
        }

        /// <summary>
        /// N:1 business_unit_orders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_orders")]
        public BusinessUnit Orders_OwningBusinessUnit
        {
            get
            {
                return this.GetRelatedEntity<BusinessUnit>("business_unit_orders", null);
            }
        }

        /// <summary>
        /// N:1 campaign_orders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("campaignid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("campaign_orders")]
        public Campaign Orders_SourceCampaign
        {
            get
            {
                return this.GetRelatedEntity<Campaign>("campaign_orders", null);
            }

            set
            {
                this.OnPropertyChanging("Orders_SourceCampaign");
                this.SetRelatedEntity<Campaign>("campaign_orders", null, value);
                this.OnPropertyChanged("Orders_SourceCampaign");
            }
        }

        /// <summary>
        /// N:1 lk_salesorder_createdonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_salesorder_createdonbehalfby")]
        public SystemUser Orders_CreatedBy_Delegate
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_salesorder_createdonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 lk_salesorder_modifiedonbehalfby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_salesorder_modifiedonbehalfby")]
        public SystemUser Orders_ModifiedBy_Delegate
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_salesorder_modifiedonbehalfby", null);
            }
        }

        /// <summary>
        /// N:1 lk_salesorderbase_createdby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_salesorderbase_createdby")]
        public SystemUser Orders_CreatedBy
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_salesorderbase_createdby", null);
            }
        }

        /// <summary>
        /// N:1 lk_salesorderbase_modifiedby
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_salesorderbase_modifiedby")]
        public SystemUser Orders_ModifiedBy
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("lk_salesorderbase_modifiedby", null);
            }
        }

        /// <summary>
        /// N:1 manualsla_salesorder
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_salesorder")]
        public SLA Orders_SLA
        {
            get
            {
                return this.GetRelatedEntity<SLA>("manualsla_salesorder", null);
            }

            set
            {
                this.OnPropertyChanging("Orders_SLA");
                this.SetRelatedEntity<SLA>("manualsla_salesorder", null, value);
                this.OnPropertyChanged("Orders_SLA");
            }
        }

        /// <summary>
        /// N:1 opportunity_sales_orders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opportunityid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("opportunity_sales_orders")]
        public Opportunity Orders_Opportunity
        {
            get
            {
                return this.GetRelatedEntity<Opportunity>("opportunity_sales_orders", null);
            }

            set
            {
                this.OnPropertyChanging("Orders_Opportunity");
                this.SetRelatedEntity<Opportunity>("opportunity_sales_orders", null, value);
                this.OnPropertyChanged("Orders_Opportunity");
            }
        }

        /// <summary>
        /// N:1 order_customer_accounts
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("order_customer_accounts")]
        public Account Orders_Customer
        {
            get
            {
                return this.GetRelatedEntity<Account>("order_customer_accounts", null);
            }

            set
            {
                this.OnPropertyChanging("Orders_Customer");
                this.SetRelatedEntity<Account>("order_customer_accounts", null, value);
                this.OnPropertyChanged("Orders_Customer");
            }
        }

        /// <summary>
        /// N:1 order_customer_contacts
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("order_customer_contacts")]
        public Contact Orders_Customer2
        {
            get
            {
                return this.GetRelatedEntity<Contact>("order_customer_contacts", null);
            }

            set
            {
                this.OnPropertyChanging("Orders_Customer2");
                this.SetRelatedEntity<Contact>("order_customer_contacts", null, value);
                this.OnPropertyChanged("Orders_Customer2");
            }
        }

        /// <summary>
        /// N:1 quote_orders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quoteid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("quote_orders")]
        public Quote Orders_Quote
        {
            get
            {
                return this.GetRelatedEntity<Quote>("quote_orders", null);
            }

            set
            {
                this.OnPropertyChanging("Orders_Quote");
                this.SetRelatedEntity<Quote>("quote_orders", null, value);
                this.OnPropertyChanged("Orders_Quote");
            }
        }

        /// <summary>
        /// N:1 sla_salesorder
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slainvokedid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_salesorder")]
        public SLA Orders_LastSLAApplied
        {
            get
            {
                return this.GetRelatedEntity<SLA>("sla_salesorder", null);
            }
        }

        /// <summary>
        /// N:1 system_user_orders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("system_user_orders")]
        public SystemUser Orders_OwningUser
        {
            get
            {
                return this.GetRelatedEntity<SystemUser>("system_user_orders", null);
            }
        }

        /// <summary>
        /// N:1 team_orders
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_orders")]
        public Team Orders_OwningTeam
        {
            get
            {
                return this.GetRelatedEntity<Team>("team_orders", null);
            }
        }

        /// <summary>
        /// N:1 transactioncurrency_salesorder
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
        [Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("transactioncurrency_salesorder")]
        public Currency Orders_Currency
        {
            get
            {
                return this.GetRelatedEntity<Currency>("transactioncurrency_salesorder", null);
            }

            set
            {
                this.OnPropertyChanging("Orders_Currency");
                this.SetRelatedEntity<Currency>("transactioncurrency_salesorder", null, value);
                this.OnPropertyChanged("Orders_Currency");
            }
        }
    }
}