//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VA.TMP.DataModel.OptionSets
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public enum CampaignResponse_Channel
    {
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Appointment = 5,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 1,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fax = 3,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Letter = 4,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Others = 6,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Phone = 2,
    }
}