//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VA.TMP.OptionSets
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public enum crme_veteransensitivitylevel
    {
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SensitivityLevel0 = 935950000,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SensitivityLevel1 = 935950001,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SensitivityLevel2 = 935950002,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SensitivityLevel3 = 935950003,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SensitivityLevel4 = 935950004,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SensitivityLevel5 = 935950005,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SensitivityLevel6 = 935950006,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SensitivityLevel7 = 935950007,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SensitivityLevel8 = 935950008,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SensitivityLevel9 = 935950009,
    }
}