//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VA.TMP.DataModel.OptionSets
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public enum CustomerAsset_RegistrationStatus
    {
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 192350004,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProgress = 192350002,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Registered = 192350003,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 192350000,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unregistered = 192350001,
    }
}