//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VA.TMP.OptionSets
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public enum cvt_facilityapprovalstatus
    {
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approve = 917290001,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClickheretoAPPROVEorDENY = 917290000,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deny = 917290002,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReviewPending = 803750000,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReviewedAndConfirmed = 803750001,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReviewedAndUpdated = 803750002,
    }
}