//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VA.TMP.OptionSets
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public enum cvt_systemuser_cvt_organization
    {
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Biomed = 917290000,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CredentialingPrivileging = 917290001,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OIT = 917290002,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TelehealthProgram = 917290003,
    }
}