//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VA.TMP.DataModel.OptionSets
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public enum Lead_Status
    {
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disqualified = 2,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Open = 0,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Qualified = 1,
    }
}