//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VA.TMP.OptionSets
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public enum mcs_integrationresultmcs_status
    {
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Complete = 803750002,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 803750003,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_RetrySuccess = 100000000,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvestigationRequired = 803750001,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitingForResponse = 100000001,
    }
}