//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VA.TMP.DataModel.OptionSets
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public enum ProcessTrigger_StatusReason
    {
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 917290001,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 917290002,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProgress = 917290000,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 1,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 2,
    }
}