//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VA.TMP.OptionSets
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public enum TMPResource_Status2
    {
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcquisitionProcess = 917290000,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deployed_Installed = 917290002,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeploymentProcess = 917290001,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OutOfUse = 917290003,
    }
}