//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace VA.TMP.OptionSets
{
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.71")]
    public enum workflow_scope
    {
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessUnit = 2,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Organization = 4,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Parent_ChildBusinessUnits = 3,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 1,
    }
}